### ISSUE TITLE
HE to RF converters eating up energy

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1080]
EDIT: i realized what the ACTUAL problem was

I have a set of HE to RF converters for some thermal series machines, despite the machines being inoperational, instead of reaching the stored energy cap the converters continue infinitely eating up power, and overloading the grid, Sorry for any confusion my last post might have caused

Thanks
-Chosen

**Comment by HbmMods** [comment]
What machines are you trying to power? I've noticed that certain mods implement the RF API in weird ways, especially BuildCraft, so there may not be a whole lot I can do about it. In any case you can limit the amount of energy used by the converters with diodes.

**Comment by TheChosenIndividual** [comment]
they are all thermal foundation and i think expansion machines, the pulverizer, magma crucible, 2 fluid transposers and a lava fabricator from minefactory reloaded, i am working into limiting their input with redstone power switches, however i have noticed that the converter energy cap is gone, which makes them eat energy indefinitely, hope that clears things up and dont be afraid to let me know if you need any more info

Thanks
-Chosen

**Comment by HbmMods** [comment]
There's been some more info coming in about this recently, the issue comes from the fact that NTM's power grid and the RF grid work quite differently, and that many mods have different oddities regarding their implementation of the system. It's unlikely that I can ever properly fix this without imposing a transfer limit on the converter again (and even then, the converter would still eat as much power as the limit even when that's not necessary), so the only way of avoiding this issue is by using diodes to limit the amount of power going through the converter.
