### ISSUE TITLE
Item Suggestion

### ISSUE THREAD

**Issue by Princelion33** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1087]
Subject: Addition of Diamond Bedrock Ore for your Minecraft mod

Dear HbmMods,

Firstly, I want to express my appreciation for the incredible work you have done on your Minecraft mod. I have recently been using your mod and have been thoroughly impressed by its features and gameplay. However, I have a suggestion to further enhance it.

I noticed that there is currently no Diamond Bedrock Ore included in your mod, and I believe it would be a fantastic addition. Diamond is an iconic element in Minecraft, and introducing Diamond Bedrock Ore as a new item obtainable through the Large Mining Drill would bring an exciting new dynamic to the gameplay.

As an avid player, I have come up with a few ideas for implementing this ore in your mod. It could be made rarer than other ores, with a distinct texture to set it apart. Additionally, you could consider adding new crafting recipes or uses for the Diamond Bedrock Ore, which would encourage players to mine it strategically and utilize it in various ways.

I understand that you may be busy, but I genuinely hope you will take this suggestion into consideration. I firmly believe that the inclusion of Diamond Bedrock Ore in your mod would make it even more appealing to the Minecraft community.

Thank you for your time and the outstanding work you have already done. I am excited to see what the future holds for your mod, and I am confident that you will continue to impress the Minecraft community with your updates.

Best regards,
Princelion33

**Comment by JameH2** [comment]
Diamond may be iconic in Minecraft but its not iconic in NTM

Diamonds are practically useless in ntm, except for a few recipes and your diamond sword and armor wont matter to the 50 bmg rounds made from other materials

**Comment by Princelion33** [comment]
> Diamond may be iconic in Minecraft but its not iconic in NTM
> 
> Diamonds are practically useless in ntm, except for a few recipes and your diamond sword and armor wont matter to the 50 bmg rounds made from other materials

Yes, but it could be good for a massive diamond farm for certain uses when combined with other mods that require a huge amount of diamonds.

**Comment by JameH2** [comment]
Yeah bob didnt make this mod for other mods sorry

Also suggestions arent allowed here

**Comment by Princelion33** [comment]
> Yeah bob didnt make this mod for other mods sorry
> 
> Also suggestions arent allowed here

Okay, but why are you telling me this? There are plenty of other people who have created features that are still open or these are suggestions, and these people ask for things that require a lot of development time, new complex machines, or I don't know. I'm just asking for a small item and I'm just trying to ask...

**Comment by LePeeperSauvage** [comment]
Because if Bob added every small items everyone decided to suggest (which by the way, isn't allowed here) the mod would be even more of a mess than Orespawn, and he wouldn't have time to develop anything else on the mod. NTM exists for itself, not other mods, you or anyone play, no offense. The only times you'll see integration is for major mods, or other tech mods where they have similar items (i.e gas masks) and cause problems with gameplay.
After all, if you need that diamond farm, why not install a mod that adds that instead? But that shouldn't even be needed, you can make diamonds with a press and crushed obsidian. Check the recipes.
As for balance, it correlates with my first point : We can't add every feature everyone suggest, this is no exception here.
"Why are you telling me this" he, and me too, get to see some stuff, and we also know your suggestion is not getting added.

If there's anything else you'd like to know, ask away.

**Comment by OlorinIV** [comment]
> > Yeah bob didnt make this mod for other mods sorry
> > Also suggestions arent allowed here
> 
> Okay, but why are you telling me this? There are plenty of other people who have created features that are still open or these are suggestions, and these people ask for things that require a lot of development time, new complex machines, or I don't know. I'm just asking for a small item and I'm just trying to ask...

What you're asking for is the last resource to worry about in NTM. Do you not know that NTM comes with an 8x diamond production line starting from ore? Or perhaps you didn't realize that coal and lignite ore could be nuked into diamond?
This addition would be pointless as NTM diamond production is quite OP in the first place.
