### ISSUE TITLE
(suggestion) redstone input for rbmk console. The more redstone signal, the more rod insertion. For example if u put a lever on the back of the console and u activate it all of the rods go all the way in. But if the signal is weaker then they insert partially. This will allow for partial shutdowns and would be very cool.

### ISSUE THREAD

**Issue by Ade0924** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1104]

**Comment by HbmMods** [comment]
There is absolutely no sensible use-case for this, as redstone only makes sense in automation, but there would still be no way to detect any variables like depletion or heat using redstone for the system to respond to, and if used by hand with levers you might as well just use the console outright.

A much more sensible approach would be special redstone-over-radio devices that could both read stats as well as respond to things like heat or depletion, this would also allow groups of control rods to be targeted individually instead of just having one switch for the whole reactor, a RoR device like that is already planned.
