### ISSUE TITLE
FEnSU can overfill causing the power to go back to 0 and causing visual glitch

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1130]
I was messing around in creative with the DFC when I managed to fill up the FEnSU. The energy level went back to 0 and the wheel of the FEnSU completely disappeared.
![2023-08-03_08 30 20](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/130397363/85481d3b-f9a4-4975-9553-848162ba2bec)

**Comment by BallOfEnergy1** [comment]
The FEnSU uses the maximum `long` limit as the maximum power, so overfilling it can cause some large problems (causing the float value to overflow and break textures/values). It's not easy to fill up the FEnSU though, and there's not much of a way to fix the issue other than decreasing the maximum power storage.

**Comment by HbmMods** [comment]
Should be fixed in the most recent version, DFC beams now have a cap on how strong they can be, preventing overflows and negative values. Hasn't been tested with binary star setups so I'm leaving it open until I get confirmation.

**Comment by OlorinIV** [comment]
Wouldn't it be better to decrease the power buffer to like 9.20EHE, rather than putting a cap on DFC beams? Even with a high energy field jammer they cannot generate more than 10.8PHE/t, which is capped by the size of the core's tanks. Perhaps shrinking FEnSU's power buffer a little bit could also fix the problem...
