### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Skyliner77** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1148]
How do I prioritize HBM's metals after processing ores, I always get IC2's, Ender IO's, or AE2's versions which can be a pain in the ass. I tried tinkering with Forge's ore dictionary but it seems to have no result.

**Comment by HbmMods** [comment]
For the sake of processing it doesn't actually matter what exact type of an item you get because they are all interchangeable in crafting anyways and NTM filters allow filtering by ore dictionary. If you really need a way to convert them automatically, I believe Mekanism has an automated ore dictionary unifier.

**Comment by OlorinIV** [comment]
Try adding an 'a' in front of the file name or whatever that will make the mod load before other tech mods.
