### ISSUE TITLE
Power detector isn't working.

### ISSUE THREAD

**Issue by rattlemebones1** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1198]
Mod version 4707, I can't seem to get the power detector to work properly. An image of the settup: 
![Screenshot 2023-09-15 221544](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/109101492/7b0a5a87-d733-42e1-82b1-ee62a03bf524)
Power is flowing, I can hear it from the electric heaters. The detector just isn't turning on.

**Comment by HbmMods** [comment]
If you replace the detector with something else like an electric furnace, does it charge?

**Comment by rattlemebones1** [comment]
Yes, it instantly fills up. I tried with both power cut to the heaters and with it reconnected, and then I replaced it with the detector again. Detector just doesn't get power.

**Comment by BallOfEnergy1** [comment]
At some point it might have changed where power has to be flowing through the block, though I'm not sure why that would be the case.

**Comment by HbmMods** [comment]
I assume the issue is because of the network's demand being so high that the amount of power supplied to the detector is rounded below 1. I made the power detectors take higher priority than most other consumers (probably not an issue because of how little power they use), could you verify whether that fixed the issue?
