### ISSUE TITLE
Ground Feedwater pump breaks reactor thermodynamic cycles

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1201]
This isnt a technical issue, but a mechanic issue, the problem is, in short, that the ground feedwater pumps from the newest version, completely eliminate the need for the completion of the reactor thermodynamic cycle, using ground water pumps (Which i will be referring to as Feedwater pumps from now on), most specifically the electrical variant, allows for the bypass of the reactor condensing cycle, and turns it into a complicated mess, basically, creating water out of nowhere, means that the reactor will be fed with water, forever, and the steam which is usually condensed and recycled, can be scrapped, vented or set to other purposes, my proposal is to change the pumps, the steam driven pump is better, as it allows for realistic reactor cooling isolation, when turbines fail or regular feedwater pumps are unavailable, however, it should NOT create low-pressure steam, as this allows for WATER DUPLICATION, which eventually clogs the system unless you vent it somehow, and the electrical pump should be, in my opinion, removed, instead replaced by an actual feedwater pump, which, when powered, allows for a somewhat realistic experience of pushing water through the system, and just fuel the initial feedwater with barrels, from further testing i can also say, that the steam pump is...horribly inefficient, and does NOT work for Reactor Cooling Isolation, maybe a more industrial rugged steam driven pump? i know realism isnt something that is relevant in HBM, but it would make thinks, severely more awesome, thanks for reading

-Chosen

**Comment by 70000hp** [comment]
I am sorry, the old alternative was a small barrel that could magically produce water, and you are complaining about *realism*?

**Comment by TheChosenIndividual** [comment]
> I am sorry, the old alternative was a small barrel that could magically produce water, and you are complaining about _realism_?

Im not really complaining about the realism of the pumps, but how that realism, breaks more realism, as in, it makes meltdowns significantly easier, or harder, to prevent, the realism of the pumps is there, and i am aware of it, however i feel like the way this was set up could be better

**Comment by TheChosenIndividual** [comment]
Also, Edit: Steam groundwater pumps DO work for emergency RCIC, however you need many of them, but that isnt a problem since they are subliminally cheap

**Comment by JameH2** [comment]
The weird thing about this is that this specific issue was already possible before by just using heavy infinite water barrels

**Comment by TheChosenIndividual** [comment]
> The weird thing about this is that this specific issue was already possible before by just using heavy infinite water barrels

You´re right, but the problem was that you´d need a lot of them to be able to produce the same effect, HOWEVER, according to my tests, a single Zirnox Reactor can be fueled by ONE electrical pump

**Comment by HbmMods** [comment]
> that the ground feedwater pumps from the newest version, completely eliminate the need for the completion of the reactor thermodynamic cycle

Open cycle reactors were already a thing beforehand, difference being you had to use magic infinite water barrels instead of larger pumps. Despite the pumps being better, open cycles are still discouraged because an interruption in the pumps will prevent the reactor from cooling, something that can never happen in closed cycles.

> creating water out of nowhere

They are groundwater pumps, they pull water out of the ground. Nor do I see how that would be an issue because of how cheap and trivial water is as a resource.

> it should NOT create low-pressure steam, as this allows for WATER DUPLICATION

For one, clogging is a non-issue so long as you keep the open cycle and the pump's steam cycle separate and two, the pump's entire purpose is to create water so I don't understand the point about water duplication. If you have an open cycle and constantly add water, then obviously you'll have to remove that water on the other end, closed cycles never required pumps or anything like that in the first place.

> from further testing i can also say, that the steam pump is...horribly inefficient, and does NOT work for Reactor Cooling Isolation

You're using a steam-powered earlygame water source for an open cycle nuclear reactor, there's like three issues in that sentence alone.

**Comment by TheChosenIndividual** [comment]
> > that the ground feedwater pumps from the newest version, completely eliminate the need for the completion of the reactor thermodynamic cycle
> 
> Open cycle reactors were already a thing beforehand, difference being you had to use magic infinite water barrels instead of larger pumps. Despite the pumps being better, open cycles are still discouraged because an interruption in the pumps will prevent the reactor from cooling, something that can never happen in closed cycles.
> 
> > creating water out of nowhere
> 
> They are groundwater pumps, they pull water out of the ground. Nor do I see how that would be an issue because of how cheap and trivial water is as a resource.
> 
> > it should NOT create low-pressure steam, as this allows for WATER DUPLICATION
> 
> For one, clogging is a non-issue so long as you keep the open cycle and the pump's steam cycle separate and two, the pump's entire purpose is to create water so I don't understand the point about water duplication. If you have an open cycle and constantly add water, then obviously you'll have to remove that water on the other end, closed cycles never required pumps or anything like that in the first place.
> 
> > from further testing i can also say, that the steam pump is...horribly inefficient, and does NOT work for Reactor Cooling Isolation
> 
> You're using a steam-powered earlygame water source for an open cycle nuclear reactor, there's like three issues in that sentence alone.

I agree with HBM´s feedback, and ill respond accordingly
1. You are correct, however as i stated in one of my previous comments, was that before it was more expensive to produce the same effect, needing several infinite water barrels, among other things
2. the problem with this is that it makes the steam cycle severely more expensive and complicated, requiring two separate sets of steam loops in a closed loop, and an open loop makes the reactor more prone to overheating
3. You're....right...im sorry i apologize for that, i wasnt seeing it as an early game machine, my bad

**Comment by HbmMods** [comment]
> requiring two separate sets of steam loops in a closed loop

Not sure what you mean by that, you don't need a pump running constantly with a closed loop, you just fill it once (even buckets work) and then you're done. The groundwater pumps haven't really changed how closed loops work at all.

**Comment by TheChosenIndividual** [comment]
> > requiring two separate sets of steam loops in a closed loop
> 
> Not sure what you mean by that, you don't need a pump running constantly with a closed loop, you just fill it once (even buckets work) and then you're done. The groundwater pumps haven't really changed how closed loops work at all.

I apologize its just that....im not very good at expressing myself, but in short, i mean the reactor loop water and the pump loop water, however venting the low-pressure steam also works, but adding it to the system just duplicates it and causes....annoying issues...

**Comment by OlorinIV** [comment]
However I'm quite interested in the idea that pumps shouldn't be able to pull groundwater endlessly. I had expected before the update that pumps should be placed above water bodies, similar to what the hephaestus does.

**Comment by funnyman8** [comment]
Honestly I never found producing the water for an open loop to be an issue in NTM, but instead getting rid of all the LPS left over. Often times I found using the inverse, condensing it then pumping the water into a barrel with a heavy infinite water tank in the output, was the easiest, but at that point it's completely useless because at that point, it would be trivial to actually run a closed loop. Even then, I wouldn't consider the new pumps to at all break closed loops even if you *could* mass-vent steam out of chimneys or smth (which would be really neat imo), because at its core it's just far easier to set up a couple of condensers (You only need a few to run a zirnox, and an aux tower is still rather cheap while completely satisfying it, and that's all just steel and concrete), while an open loop requires constant water pumping, possibly extra infrastructure to prevent clogs and backups, and has the possibility of actually causing a LOCA just by losing power/steam for reactors.

**Comment by TheChosenIndividual** [comment]
Thats my point, these pumps promote open cycle reactors, which are MORE EXPENSIVE than closed cycle reactors

**Comment by OlorinIV** [comment]
But HOW? Don't you realize what you're talking about is totally nonsense? 

The update offered players a choice that _might_ encourage them to build open cycles - which still isn't a feasible option because NTM doesn't have an efficient way to void liquid efficiently and automatically. We're talking about _possibilities, choices and options_ which players may or may not take, subject to their own different purposes. And such uncertain and optional pathways somehow PROVOKED you leading to the opinion that e-pumps should be deleted. Whoa. I had expected this to be more of a _personal_ issue. How about forking the project and delete e-pump and make a build of your own and pretend that the author never added it.

Talking about the sole purpose of 10000mB/t electric pumps. As we all know 10000mB/t water equals 10mB/t deuterium, which is just enough to fuel one fusion reactor. Before the update this was achieved by stacking 20 heavy infinite water barrels, much less performant than one single pump. And not to mention giant electrolysis factories that powered endgame reactors, which can easily consume up to thousands mB/t of LH2 and LOX. I cannot imagine someone who had played into the mod to consider such thing unnecessary or even 'game-breaking'.

**Comment by OlorinIV** [comment]
But HOW? Don't you realize what you're talking about is totally nonsense?

The update offered players a choice that _might_ encourage them to build open cycles - which still isn't feasible because NTM doesn't have an efficient way to void liquid automatically. It's just a possible choice players may or may not take, subject to their own different purposes. And such optional thing somehow _provoked_ you leading to the opinion that e-pumps should be deleted. Whoa. I had expected this to be more of a _personal_ issue. How about forking the project and delete e-pump and make a build of your own and pretend that the author never added it.

Talking about the sole purpose of 10000mB/t electric pumps. As we all know 10000mB/t water equals 10mB/t deuterium, which is just enough to fuel one fusion reactor. Before the update this was achieved by stacking 20 heavy infinite water barrels, much less performant than one single pump. And not to mention giant electrolysis factories that powered endgame reactors, which can easily consume up to thousands mB/t of LH2 and LOX. I cannot imagine someone who had played into the mod to consider such thing unnecessary or even 'game-breaking'.

And realistic pumps & pipes, BRUH. You don't major in chemical engineering, do you?

**Comment by BallOfEnergy1** [comment]
This is literally an argument of realism in NTM
