### ISSUE TITLE
Extreme FPS Loss in certain GUI

### ISSUE THREAD

**Issue by Iamjusthereforthegames** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1203]
### Describe the bug
Whenever I open steel crates, turbines, and some other things, the game slows down to 1 fps. It doesn't happen with iron crates, and it never happened in older versions. Idk why it's happening. I do have a lot of other mods, but considering it didn't happen with those same mods in earlier versions, I don't think it applies.

**Comment by HbmMods** [comment]
Steel crates haven't changed at all in the past year, nor are iron and steel crates any different except for the texture and slot count. Sounds more like a conflict or a driver issue, could you run a profiler like spark or lag goggles?

**Comment by Howdidibreakit** [comment]
(this is the same person but on a different account idk why i have two accounts) I'll see what mods are causing it because it's EXTREMELY laggy with turbines.

**Comment by Iamjusthereforthegames** [comment]
optifine caused it.

**Comment by Howdidibreakit** [comment]
It's not an optifine issue. It's something weird with the blast furnace's code. Pretty much everything that slows down my game recycles the blast furnace's gui code, since it can do fluids and also storage. At some point you decided to change both the steel and desh crates to be very similar, and use a much more standard format. I'm not sure why that format causes the problems, maybe it's due to it trying to find the nbt data for every item in your inventory, then seeing an item that contains other items from another mod, and getting confused, since crates are now as radioactive as their contents. Either way, the best fix I can think of to get this compatibility issue to work is to make steel and desh crates like iron crates. The other blocks that cause lag, namely, the turbine and spent fuel rod drum, actually do reuse some blast furnace code, but they still lag like crazy and i don't know why. I think the main issue with the crates is that the steel and desh ones do not call for their tilentity data despite being machines. I don't know why that'd do that, but I'm sure it's the problem.

**Comment by Howdidibreakit** [comment]
i got the solution but still have no idea why the problem happens. maybe it's because of tinker's construct trying to figure out which ingot is which and getting confused and screaming at me.

**Comment by Iamjusthereforthegames** [comment]
THE WAILA MOD
THE WHAT AM I LOOKING AT MOD DOES THE THING.
THAT'S THE PROBLEM
AAAAAAAAAAHAHAHAHA! I DID IT!!!! WOOOO!

**Comment by Iamjusthereforthegames** [comment]
It's a specific issue where when you open the gui while looking at the thing, it fucks everything up
