### ISSUE TITLE
[Question] How can i change NTM fluid temperatures and heat capacity?

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1205]
Recently i´ve been working with Molten Thorium Salt, however i have run into issues, regarding the fact that the reactor i want to use (Reactor Bolshoy moschnosti kanal´ny...or RBMK for lame-o-s) does NOT have the sufficient thermal capacity to withstand it, so, instead of posting an enhancements and likely be obliterated by logic, im just asking, to people who know more about programming and about the game´s code than i do, if you can help, PLEASE feel free to comment on this post and i will provide any additional information you might need, thanks

-Chosen

**Comment by OlorinIV** [comment]
All attributes of liquids stored here: src/main/java/com/hbm/inventory/fluid/Fluids.java
What you're asking for is in line 325. Change 1600 into another smaller number. 
If you want to make the heat capacity stay the same, go to line 526&527 and change 400 to scale linearly with your new ΔH.

Aside from fork and build on GitHub,  you can also decompile via Recaf which only needs the released mod jar file. (And Recaf)
1. Download Recaf. https://github.com/Col-E/Recaf/releases/download/2.21.13/recaf-2.21.13-J8-jar-with-dependencies.jar
2. Dbl click jar to open, go to 'Config' and switch display-class mode to table.
3. Drop the mod into the window. Go to classes/com/hbm/inventory/fluid/Fluids and open.
4. Click 'Methods' and then open 'Index(2)'. 
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/104282311/4e9930df-c993-4170-b840-96e72920ea0f)
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/104282311/07aac090-40ea-45e5-b465-b4b5a1ffa113)
So 'A' refers to line 197 in the original GitHub .java file.
5. Pull down until you see line 325. Change SIPUSH 1600 to SIPUSH  x. Ctrl+s to save your changes, otherwise you have wasted your time. If the window border flashes green then you succeeded to save.
6. Click on 'File' an then 'Export program', rename your new file to xxx.jar or just save on your original mod jar to replace it.

**Comment by OlorinIV** [comment]
There. GitHub issues is not a game forum, and we aren't posting blogs. I hope this is going to be the last time you post gameplay questions that do NOT concern bugs, since I learned the above all by myself through my browser and search engine and I expect you to be able to do the same.

**Comment by TheChosenIndividual** [comment]
Thank you for your input kind stranger, i...do agree with the github thing, and as such ASK that you direct me to any forums or additional resources you might know of, it would be a life saver, also, i was able to complete the changes, and after just 5 hours of wall to head banging i managed to do it, thank you again

-Chosen
