### ISSUE TITLE
Howitzer?

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#123]
I see mini nuke shells and silver bullets, but where is the Howitzer to shoot them?

**Comment by UFFR** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Thu, 17 Dec 2020 08:27:32 -0800
joey-lg <notifications@github.com> wrote:

> I see mini nuke shells and silver bullets, but where is the Howitzer
> to shoot them?
> 

No, they're for the "Digamma Folly", an unfinished weapon, don't craft
them because they have no uses at this point in time.
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE6yGL8bTdIimDHw0jHN78URkEn8UFAl/bh1IACgkQHN78URkE
n8VVyQwAiV6wGHgp9JSEQJyH96hHHVkqgOwCfB+TAz12UBK3ujqeyNOx6S6yb5Ob
PupgXKXuuX0vhF8K4ROZydiShAh6SpAiNmxCj/a/nUtuTq2TyM1hTCKu2G9zNuXe
LYrpcA8p7fxeKCf5nTPTEIXwrWLiY+1LPwpR9YCvo1kW3wQl9mzaErGuh3zMQwyv
i2uiPGZQyrQZpEfZgOx2XG9GLfA4v1jDDfx7Fwi6uwWkxUMyht6Zi4JVt+vxfRGg
pe9HRD1xy9wcfqD4J7fjd+3IrVSnnpSPvFwbZs9z7MsvqS4Too8GuOKMWbjCWkm6
D6tWXjXuxpt0dBwFIDgYwQ68dCC5pyJ2M9r3WbruaRqRbY/gl5y7kek3v8U75SHb
YGJpXMm+tZ6w4tolP1BhQVDzLuz1V/Q+JW0a19RKmWzx6MJ9rTHPepH8t55fD3MB
OIA1+e9qIHxMoep9wN2kj+oD7AfVeJgTjNWVyfAfK77PX8xMFMOKwJv0vxV42NTo
kWGjXcOa
=qQLT
-----END PGP SIGNATURE-----

**Comment by Nos74** [comment]
you gotta find me some nicotine first, only then can i reveal the weapon's whereabouts
