### ISSUE TITLE
Balefire explosion does not work properly underground

### ISSUE THREAD

**Issue by physikpro** [HbmMods/Hbm-s-Nuclear-Tech-GIT#125]
If you detonate a balefire bomb underground, it creates a crater on the surface.
I use the version hbm_1.0.27_X3697. 

I also found a small incompatibility with the Minecraft Comes alive mod. In this mod villagers are replaced with human-like individual models. There are guards and it is possible to create families.  The problem is that when they are mutated to zombies by radiation they do not become the zombies from the mod but vanilla zombies. These cannot be healed. It is also not the case that they die and drop their items. You can also normally resurrect them, which is then no longer possible. It would be nice if zombification worked like in Vanilla or at least if there was an option to turn off zombification in case of radiation.

Finally, I would like to praise this for being such a versatile and living mod. I discovered it a few years ago and since then this mod has matured a lot. I hope that the development will continue. In my opinion the best technology mod.

**Comment by UFFR** [comment]
I believe that the first issue is not really a bug, since that's just 
how Balefire explosions work.

**Comment by HbmMods** [comment]
That is correct, the balefire explosion's wonkyness is a result of balancing functionality and performance. The Tsar from Rival Rebels does the exact same thing, no matter where you detonate it, it will always cast the crater from the sky to the terrain. There's a few small ways I could improve it, but until we find a better system that still has the desired results, this is what we'll have to stick with.

Zombification doesn't create villager zombies on purpose, as mutation by radiation is intended to be uncurable with golden apples. I didn't expect that to work with MCA villagers as well (it seems like they inherit from the vanilla zombie classes) but even then I don't see that as much of an issue. However, adding a general config to turn off mob mutation due to radiation seems like a reasonable addition, I'll look into that.
