### ISSUE TITLE
Big Memory Leak with Recent Release (1.0.27_X4795)

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1258]
The most recent release (1.0.27_X4795) has cause memory usage on task manager to go up by ~5MB a second. Naturally, crashing the game. This was tested in a default superflat world.

Tested this with the previous release and that does not have this issue.

**Comment by HbmMods** [comment]
Can't replicate, on a fresh superflat world, the RAM usage climbs to ~650MB due to temporary objects created for various calculations before the GC kicks in and reduces it back to ~300MB. Did you have any machines in that world, perhaps one of those that got rewritten in the previous update? Radars, launch pads, missiles, anything like that?

**Comment by CapitalismWouldveWorked** [comment]
I was wrong, I was testing with LWjgl3ify using java 17 and noticed switching back to the default java fixed the issue, this was an issue without even hbm in the pack, sorry for the confusion.
