### ISSUE TITLE
Ducks not spawning with O only once

### ISSUE THREAD

**Issue by LavaHoleD** [HbmMods/Hbm-s-Nuclear-Tech-GIT#129]
So, I just updated my modpack and server, and got the verification of this.
You can just spam ducks spawning by disconnecting and relogging, so yeah it's a bug.
Also as i've said I suggest to make the option to disable this feature inside the config. (It's only a suggestion)
QUICK PROBLEM UPDATE
At the moment I could solve this at least on my server by blacklisting the duck with bad mobs.

**Comment by HbmMods** [comment]
Duck spawn is based on the player's persistent NBT tag, if relogging allows for continuous spawning of ducks that implies that the persistent tag (which, as the name implies, is supposed to be persistent) gets cleared which in theory could lead to all sorts of nasty behavior.

Ducking has been tested on a ("blank") eclipse test server, forge server and a thermos server with quite a few mods on it, ducks aside persistent data disappearing is most likely due to some wacky server software or mod which I would say is worth investigating.

Either way I added a general config that turns off both the little tooltip and the mechanic itself, which should resolve this issue.
