### ISSUE TITLE
Foundry additives that reach 16 blocks are permanently stuck that way

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1292]
### Describe the bug

Foundry additives that reach too large of a quanity can't be casted, and they also can't be used in recipies due to taking up a larger volume than the recipe buffer allows. This prevents it from being used at all.
Version is 1.0.27_X4824

**Comment by HbmMods** [comment]
Ingredients generally don't take up more space than their fraction in the recipe, i.e. if the recipe requires 50% carbon, the crucible won't accept more than half in carbon so that's generally not an issue unless you have other materials in there which don't belong to the recipe at all, in which case you will have to clear those out with a shovel when switching recipes.

**Comment by ghost** [comment]
I should've mentioned that this only happens when they are melted without a recipe, since then the scrap can't be re-melted into the recipe buffer or casted to decrease the amount.

**Comment by HbmMods** [comment]
Then you should avoid smelting uncastable things without recipe at all. You can still use the scrap though, by putting it in the crafting grid you can break the scrap heap in half until you have an amount that you can use.

**Comment by ghost** [comment]
Ah ok, thanks.
