### ISSUE TITLE
Combination oven recipe for ethenol is less efficiant than Shredder + Chem plant

### ISSUE THREAD

**Issue by Ashen-sysadmin** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1294]
Instead of producing 3 sugar, the Combination oven produces 2 sugar + 50 ethanol units.
Sugar is converted at a 1:100 rate to ethanol in a chem plant or liquidizer. 

Using the oven produces less total ethanol, despite being the more complicated processing chain. Is this intended?

**Comment by HbmMods** [comment]
I wouldn't say combination ovens are more complicated, rather the opposite. Even including their power source, they're smaller, easier to run, don't need any extra infrastructure and do effectively two recipes at once (sugarcane to sugar and one of those sugar piles to ethanol), so I would argue having this minor penalty in total possible ethanol (250mB instead of 300) is justified.

**Comment by Ashen-sysadmin** [comment]
The issue is that you'd still be using a chem plant to process the 2 sugar, so the convenience gains are marginal. -- You only skip the shredder. Currently running my early-game (post oil, pre-nuclear) base on biofuel , loving the mod thusfar.
