### ISSUE TITLE
Why is the Hydrogen Peroxide not filling the Acidizer?

### ISSUE THREAD

**Issue by VeiTheOne** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1307]
So, while I was trying to figure out the _apparent_ new pressure thing for the Osmoridic Solution, which I don't understand at all, I found out the Acidizer was like "Nope, not filling up". Why is that?

Running X4845, didn't feel like updating to latest since I haven't played MC in a while, and saw the change log for the newest, saw nothing about this issue, and a visual bug I found in nuclear explosions revolving around snow. Might as well say now, Tom'ed the world in darkness.
![Why?](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/82922007/b2aff096-fbe7-40dc-a7dc-0143dfda6e04)

**Comment by HbmMods** [comment]
> So, while I was trying to figure out the apparent new pressure thing for the Osmoridic Solution, which I don't understand at all

Pressure is just an extra stat that fluids can have in internal tanks, and compressors just increase that stat by one. I think Osmiridic Solution needs a pressure of 5PU, that would be five compressors with the first being set from 0->1, the second to 1->2 and so on. You can simply place the compressors next to one another so that the ports align, or you can use pipes, pressurized fluids can use the same pipes as unpressurized fluids.

> Acidizer was like "Nope, not filling up". Why is that?

I remember the acidizer only having an internal acid capacity of 8,000, while the fluid barrels have a volume of 16,000. Those containers can't be filled or unloaded partially, so it can't fill the acidizer at all. Either use smaller containers or connect the acidizer to an external source, like a larger tank or the chemical plant directly.

**Comment by Shibva** [comment]
So how do you compress these fluids? Hes a friend of mine and came to me first regarding the issue/question. Its a new feature and checking through the changelog I have found nothing regarding this shift apart from something being mentioned in the RBMK. (my assuptions this change was made in the added: ??? changelog).

If you can give me some detailed info regarding this and how its works and what can be used to pressurize it (exact names of blocks, methods, etc) I will make a crude entry to establish the new feature on the wiki to avoid further confusion (documentation is nonexistent when I did a dive, so I will make a crude page). From there, ill leave it for people like UFFR to correct any format errors. Tis the least I can do


In additon, the universal fluid barrel (not the water one) was tried by him and it was not filling it, so I'm guessing something was missed

**Comment by HbmMods** [comment]
> So how do you compress these fluids?

Like I said, using a compressor. Large machine, dark grey frame, gold-colored drum with a piston on top, 3x4 base. Pressurized fluids are only used for certain recipes mainly in the chemical plant, although there's a few direct conversions too (compressing steam turns it into the higher pressure variant instead of affecting the pressure stat and compressing blood a few times turns it into crude oil).

> (my assuptions this change was made in the added: ??? changelog).

Compression was added about half a year ago and documented in the [https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/releases/tag/1.0.27X4641](changelog.)

**Comment by VeiTheOne** [comment]
> Like I said, using a compressor. Large machine, dark grey frame, gold-colored drum with a piston on top, 3x4 base. Pressurized fluids are only used for certain recipes mainly in the chemical plant, although there's a few direct conversions too (compressing steam turns it into the higher pressure variant instead of affecting the pressure stat and compressing blood a few times turns it into crude oil).

I looked up pressurizer, and didn't find it, so that was probably cause I used the wrong name.


> I remember the acidizer only having an internal acid capacity of 8,000, while the fluid barrels have a volume of 16,000. Those containers can't be filled or unloaded partially, so it can't fill the acidizer at all. Either use smaller containers or connect the acidizer to an external source, like a larger tank or the chemical plant directly.

I also had connected it to a chem plant, and a big ass tank in input/output mode. I even placed an infinite fluid thing, nothing.

**Comment by HbmMods** [comment]
Smaller fluid containers, the infinite barrel and external connections all seem to work for me. Are you sure it's set to the correct fluid type? Did you set the connecting pipe's type? Are you sure the pipes are connected correctly?

**Comment by Shibva** [comment]
I made a link to the issue it's more putting the infinite barrel into the internal slot for the machine; I made a bug report on this; should elaborate further

**Comment by VeiTheOne** [comment]
> Are you sure it's set to the correct fluid type?

Yes, I triple checked, they all the yellowish liquid of Hydrogen Peroxide

> Did you set the connecting pipe's type? 

I was in Creative, so I used the HP pipe itself.

> Are you sure the pipes are connected correctly?

Yes. I even connected the pipe to the Acidizer to the pipe from the chem plant to tank.

**Comment by VeiTheOne** [comment]
I figured it out, my _dumb ass_ forgot the intakes for the fluids was at the TOP of the Acidizer. 😅

_**Embarrassing...**_ x''')
