### ISSUE TITLE
Crashed Spaceship chest generates broken

### ISSUE THREAD

**Issue by IbramGaunt28** [HbmMods/Hbm-s-Nuclear-Tech-GIT#138]
i noticed that since i updated from x3738 to3745, maybe earlier, one of the five chests inside the spaceship structures 
generates broken, leaving the contents on the ground.
![2021-01-26_15 27 40](https://user-images.githubusercontent.com/77243018/105858491-abd8d680-5feb-11eb-906c-7a9d1aff7bc7.png)

**Comment by HbmMods** [comment]
Has this happened more often than once? Because it rarely happens for things like ponds and caves to remove chests that have already generated.

**Comment by IbramGaunt28** [comment]
yes, all newly generated spaceships i have looked into so far were like this.

**Comment by HbmMods** [comment]
Do you have any other mods that might interfere with the world generator?

**Comment by IbramGaunt28** [comment]
yes, but not directly with the world gen, just other structures. i also just went out into new generated chunks and the very next spaceship was also with a broken chest, the same chest as in the screenshot i shared.

**Comment by IbramGaunt28** [comment]
the main point would be, which i forgot to mention, that with an older version, still with copper blocks instead of the magnets on the spaceships, the spaceships were fully intact.

**Comment by IbramGaunt28** [comment]
i just loaded a new world, same problem, maybe somehow my worldgen got glitched...

**Comment by HbmMods** [comment]
I just tested it and you are right, the chest gets destroyed every time. What's also interesting is the empty space between the chests and the meteorite blocks. As it turns out, there used to be breeding reactor blocks inside the space ship, but they got updated and became multiblocks, apparently I forgot to replace the breeding reactors with something else and the singular mutliblock block (blocklet?) deletes adjacent tiles as part of the deconstruction routine. Replacing the glitched breeding reactor blocks with nuclear furnaces fixed the issue.
