### ISSUE TITLE
reference to an older issue of textures dissapearing and a new of shadows getting stuck

### ISSUE THREAD

**Issue by Bencek123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1431]
this happened while i was looking at my RBMK and the servo part of the auto control rod has dissapered and in older times i also had the cover dissapere and the normal control rod servo also a wierd bug where the shadows get stuck
![2024-04-05_18 56 54](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/118683541/801d7608-39cb-496a-9b8b-5b13dfdbe9a8)

![2024-04-13_11 47 08](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/118683541/b739da49-8ba4-4a2e-a331-884f10672784)
lso

**Comment by HbmMods** [comment]
The shadow thing is a general issue that sometimes happens with connected texture blocks when loading a chunk, I don't know why that happens. The caps on the RBMK disappearing is in most likelyhood a vanilla bug since for those tile entities the renderer never even runs to begin with, so it's not actually a bug with the cap rendering. I doubt I can fix that one.
