### ISSUE TITLE
Chunk loading issues caused by NTM, world unplayable ATM

### ISSUE THREAD

**Issue by Futureroadkill** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1469]
After traveling around 10K blocks the terrain generation stopped and cut off into a void. stepping into the void made you free fall. no blocks are ghosting in the chunks that aren't generated. I waited for the chunks to load, after a hour nothing, shortly after the application crashed and did not close when ordered to. Here is the crash log of the events: https://mclo.gs/jbCXYoP

**Comment by JameH2** [comment]
CampFlagTileEntity from techguns

techguns is causing this

**Comment by HbmMods** [comment]
Crash log points to TechGuns, although since it's an OOM it could be about anything. Did you change anything in the config file?

**Comment by Futureroadkill** [comment]
> Crash log points to TechGuns, although since it's an OOM it could be about anything. Did you change anything in the config file?

So, I don't really use any techguns blocks I'm just there for the mobs. I just disabled the mod, it worked and I could play the world again. Now i just have lag spikes every 3 seconds unless i refresh the chunks

**Comment by HbmMods** [comment]
Lag spikes every few seconds is a somewhat common symptom of RAM barely maxing out, causing the GC to run constantly, please check how much memory is being used and adjust the amount if necessary. Otherwise, the most reliable way of finding the source of lag is using a profiler, Spark is a pretty good one for that.
