### ISSUE TITLE
MC Hopper pulling from machine inputs and outputs

### ISSUE THREAD

**Issue by garciainke** [HbmMods/Hbm-s-Nuclear-Tech-GIT#157]
When using the hopper with any of the machines, they input correctly when put on the side but then when put under machines to extract the output, they extract the items in the input, battery and output slot. 

I know there are a ton of machines and I've tried looking into what might cause that issue but I have very little knowledge of MC modding. If there was any way to help I would. Love the mod btw, probable one of my all time favs.

**Comment by ShimmeringBlaze** [comment]
It's a common issue with older machines since Bob decided not to go back and fix them to act like the newer machines, whether it's because it was too difficult without rewriting all the code, or he was just being lazy as usual, I don't know

**Comment by HbmMods** [comment]
A concrete list of machines with broken hopper integration would be useful since it has been successfully tested with quite a few machines while other ones don't work with hoppers at all due to other design reasons (the assembler for example).

**Comment by Toshayo** [comment]
The hopper doesn't extract dynosphere from battery boxes. I suppose, the problem is located here ([TileEntityMachineBattery.java:149](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/8b0e5b4ef2b4c649d94a04b50612b442f3e249ba/src/main/java/com/hbm/tileentity/machine/TileEntityMachineBattery.java#L149)), as the charged dynosphere doesn't have a charge value.
![image](https://user-images.githubusercontent.com/67237514/122557292-e4318d80-d03c-11eb-8e27-2aa1daae202a.png)
