### ISSUE TITLE
Question about the new Oil Derrick model

### ISSUE THREAD

**Issue by Jundix22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1674]
Weird question but will the new oil derrick model have an animation in the near future? Like rotating the drill string as it starts drilling. Or will it remain static as it is?

**Comment by HbmMods** [comment]
There's no animation planned, having the shaft turn wouldn't even make sense because the drill is in the center of the shaft, with the shaft being lowered down. A proper animation would show the shaft being lowered and more segments being added on top via crane, and such a complex animation would be overkill for a simple machine like that.
