### ISSUE TITLE
Suggestion for new coolant for PWR and ICF

### ISSUE THREAD

**Issue by Hinanium-Ion** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1743]
well, it seems that someone who is crazy about the extreme PWR really bothered bob. but i dont think nerf the lead coolant and PWR is a smart decision. as the lead coolant is too cheap to make, which cause it hard to balance with other coolants, why not replace it by other coolant, such as the NaK coolant? NaK alloy can also be used as coolant in the reality. moreover, KCl is actually useless in HBM, and can only be extracted from chlorocalcite by a ton of bullshit.why not adding new recipe to extract potassium for KCl solution, in order to make NaK coolant? this make sure the NaK coolant is expensive enough to become a stronger coolant compared to sodium.
or there something more expensive, like molten bismuth, which is definitely expensive enough.

**Comment by LePeeperSauvage** [comment]
The keyword in your message is "think". What you believe, even wholeheartedly, might not be the truth you could deem it to be. This statement holds true especially when you are missing great amounts of context, which so-happens to be case, presently.
None of which I am about to tell you.

However, context, which you do possess but seem to have conveniently forgotten about, is that suggestions are not taken or heard, here. And even if they were, you could always pull-request after coding it and balancing it out yourself, instead of writing a wall of text about a vague scribble of an idea onto the repository whilst marking it as an issue, while, truly, the issue seems to reside on your end and not NTM's.

**Comment by HbmMods** [comment]
I could go into detail about why the stats are the way they are and all that but I really don't care.
