### ISSUE TITLE
Logistics drones sometimes return items to the dock (specific structure)

### ISSUE THREAD

**Issue by Darek505** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1777]
### Title

 I noticed that this does not always happen, but I managed to create a structure in which this happens all the time:

![0002024-11-23_21 57 23](https://github.com/user-attachments/assets/acf342ad-4c9b-4386-9079-eb6198e4efe7)

The numbers indicate the distance in blocks,
waypoint and requester are on the same line

### What is the problem:

When you put an item in the provider, which is also present in the requester , the drone will fly out to deliver it from the provider to the requester .

However, in this structure , the drone flies to the requester, but without unloading it goes to the dock, and there, it leaves the item that was supposed to be delivered to the requester .

What is noteworthy is that if the dock was full, the drone returns to it with an unloaded box, the item will simply disappear

### Video with the problem:

https://github.com/user-attachments/assets/32312978-845a-4177-9de2-bb13bdde8095

### World, with the structure already completed:

[World.zip](https://github.com/user-attachments/files/17882307/World.zip)

### Additional:

This does not happen with transport drones, only logistic ones

This does not happen **always** in other structures, but **can** happen by accident

Sometimes, the drone can simply drop when approaching the dock, if at that moment it was transporting items to it (this bug) the items will disappear

**Comment by HbmMods** [comment]
I think I see the issue, if the target (in this case the requester) is closer to the drone than its stepsize (i.e. distance traveled per tick, for logi drones that's 0.6) it will simply cancel the step instead of shortening it, which means that depending on the angle of approach and the position of the drone before reaching the stop, it may fall short just enough to not detect the crate while still considering the waypoint to be reached. This issue may also cause the rare phenomenon where transport drones get stuck on waypoints, because they just can't move forward enough to reach it.
