### ISSUE TITLE
Worldgen lag on a server

### ISSUE THREAD

**Issue by Aspenpaw** [HbmMods/Hbm-s-Nuclear-Tech-GIT#182]
I'm running a server, and when I generated the world, the server software hung on the preparing spawn area stage, and in the server log it told me that this was an issue that needed reporting, so here I am. You may notice that Quark is also partially responsible for the worldgen lag, so I'm reporting it to them as well.
[latest.log](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/6438144/latest.log)

**Comment by HbmMods** [comment]
All that means is that the generated structures are so large that it needs to load in multiple chunks at once to generate them. It's usually not that big of a deal since it's always just 2-3 chunks being loaded at once only when there's a structure being newly generated.

Generating the spawn area can always take a while, if you do experience significant lag during gameplay because of it, please report it to the [1.12 version's issues board.](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/issues)
