### ISSUE TITLE
Issue in automating process

### ISSUE THREAD

**Issue by Weltkaiser** [HbmMods/Hbm-s-Nuclear-Tech-GIT#22]
Hi,
There is a very annoying problem with the automating process : many machines need water to be functionnal, or, there is no way to collect water automatically (there is no actual pump implemented and the others pipes from other mods don't seems to work neither).
So this is a problem in the automating process because we need to collect water manually.

I tried the Mekanism pump+fluid pipes from HBM's NTM and the pipes from thermal expension + fluid tanks from HBM's NTM, but there is no compatibility.

Thank you very much

**Comment by HbmMods** [comment]
Conventional pipes don't work since NTM machines don't use forge fluids. There are no flood gates or fluid pumps because the selection of actually usable fluids in block form only encompasses three liquids. For that reason, there is in fact a craftable infinite water tank (basically the old "infinite water out of two source blocks"-trick in item form) that fills up any water-type tank rather quickly (but not instantly - unlike the creative barrel). As of now, there are no plans for pumps or for migrating the fluid system to the conventional one shared by most other mods.
