### ISSUE TITLE
Crane is missing. Console is still there

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#310]
### Describe the bug
Im running the latest dev version, 4019
Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

### Please solve this equation to x

x²+3x-19=√(9x²)+6
Wut?

**Comment by TheForge129** [comment]
i'll help you out here
x²+3x-19=√(9x²)+6
first thing you want to do is get rid of parentheses.
√(9x²) <- The square root operation and squaring of x cancel out, then you
just square root 9. you're left with:
x²+3x-19=3x+6
now, subtract 3x from both sides:
x²-19=6
add 19 to both sides. the +19 and -19 cancel out:
x²=25
now just square root 25 and unsquare x:
x=5
it's literally just middle school level algebra

**Comment by HbmMods** [comment]
Did you even read the issue template before hitting submit?

**Comment by Joey-Destroyah** [comment]
I did. I searched in the creative inventory.
There was only the crane console. I must have gotten the wrong version.

**Comment by HbmMods** [comment]
The crane isn't a separate block, it's part of the console. You have to link it like the normal RBMK console, once it's connected the crane model will appear. Also there's no need to open issues for stuff being unfinished in unreleased dev versions, since that's quite literally part of the definition of unreleased dev versions.
