### ISSUE TITLE
Build failed! execution failed for :compile.java:

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#338]
### Describe the bug
In the git bash latest build, the build failed.
Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
txt file/log:
[log.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/7551070/log.txt)

### Please solve this equation to x

x²+3x-19=√(9x²)+6
x=5

**Comment by HbmMods** [comment]
Commits after [cb1661f](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/commit/cb1661f5d326859c4216f7b7eca24d57cff060a3) are no longer buildable on the count of the several hundred errors which come from the old energy system being removed. There's not much reason to compile this version anyway since other than implementing ne new system, nothing has changed compared to the last release from two days ago.
