### ISSUE TITLE
Battery behavior issue

### ISSUE THREAD

**Issue by GrandmaKills184** [HbmMods/Hbm-s-Nuclear-Tech-GIT#392]
When output/input mode is set it only outputs electricity. The other modes work fine, I am using the latest version. It gets pretty annoying when setting up a battery buffer with generators and machines as the batteries can only output or input at a time, never both.

**Comment by Sexygeorgeofthejungle** [comment]
Are you using the battery next to a redstone source/signal? If so, it's likely it is activating the batterys' "on redstone signal" function which is automatically set to 'output only'.

**Comment by GrandmaKills184** [comment]
No, there aren't any Redstone signals nearby, I have also tried using the input & output mode with redstone to no avail. The problem began occurring the update before the latest.

**Comment by GrandmaKills184** [comment]
No, there aren't any Redstone signals nearby, I have also tried using the input & output mode with redstone to no avail. The problem began occurring the update before the latest.

**Comment by GrandmaKills184** [comment]
Unusually, I found that when the generators are placed directly next to the battery block it functions perfectly, It just wont with any of the other connecters, cable, cable block, power pole, etc

**Comment by HbmMods** [comment]
I believe that issue was resolved with the last update, but you should test your setup again just in case. There is however one small thing you need to look out for, batteries don't send out energy in all directions (i.e. from all their sides) at once, instead they go over each output side in a fixed order. In case you have one block connected to multiple cable networks, you might have to look out for that.
