### ISSUE TITLE
Redundant

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#450]
### Describe the bug

as I was tinkering around with the radiation reduction for a building for an RBMK, I've noticed a radiation issue with the radiation the reactor gives of, even when it's sealed up. (not sure if this is supposed to happen). When using the absorbers, I've noticed that they don't work as fast, even with the max. But the thing that makes this a significant issue is that the ambiance radiation generator seems to be more effective than the elite radiation absorber. It acts faster and removes radiation at a faster rate. maybe its time for the Rad absorbers to get an upgrade for the betterment,

**Comment by HbmMods** [comment]
Rule of thumb: If you need radiation absorbers to begin with, you're already doing something wrong. Make sure that all columns that have neutrons passing through them have covers, and that the sides are properly sealed, either with solid blocks, neutron absobers or reflectors. If you have any ReaSim fuel rods, you'll have to close corners too as neutrons can move diagonally.

Where exactly did you place the radiation absorbers? Their efficiency will be heavily decreased if they are in the same chunk as the radiation source, they work best when placing them in the surrounding chunks to "wall off" radiation. That's because radiation absorbers tick once a second in the same way as most radiation sources (but not RBMKs) do, but since minecraft doesn't have a fixed order in which block updates are processed, it's seemingly random as to whether the radiation source or absorber ticks first, and depending on the case of whether the block updates or the radiation system update happens first, the radiation is either deleted as it's created or a large amount escapes in the neighboring chunks. That is amplified by the fact that the RBMK leaks radiation per tick, meaning that you almost always will have runaway rad levels.

The ambience radiation generator seems more effective (despite only removing up to 100 RAD per second) since it removes radiation once per tick.

Radiation absorbers most likely won't need a rework since the only sensible use-case is building a large buffer zone around or in buildings to protect against external radiation sources (like nearby nuclear explosions) since all other uses involve user error (be it insufficient shielding of nuclear reactors or other).

**Comment by Shibva** [comment]
ah, well that might be a good tooltip to add to the asorbers, for a rule of thumb and some stats about it

on another note, that might have been the issue, I had the thing not sealed up all the way on its sides. wonder if some visual could be added to indicate unsealed parts of a reactor, like a small visual effect or something
