### ISSUE TITLE
Cooling towers are not working

### ISSUE THREAD

**Issue by LobotomyEnjoyer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#452]
### Describe the bug

Cooling towers are not working on the newest version of NTM on a server. I tried to replace them on the new place, tried to re-connect low-pressure steam ducts, tried to use other cooling towers, tried to use other types of steam turbines but nothing worked. But they're working fine in the singleplayer.

**Comment by HbmMods** [comment]
Could you try the following things and tell me whether they work?
- Having the turbine output the LDS into a barrel instead of a cooling tower
- Placing the cooling tower directly adjacent to the turbine so that pipes aren't needed
- Connecting the LDS pipes to the bottom center (there's an unmarked connector down there) instead of the side connectors of the cooling tower

**Comment by LobotomyEnjoyer** [comment]
You can kill me rn, but I forgor:skull: to close the issue. I've fixed it, the LPS ID shifted after updating. Sorry for this.

**Comment by HbmMods** [comment]
bruh
