### ISSUE TITLE
[Enhancment] Seamless texturepack blending would be nice

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#481]
### Describe the issue

![image](https://user-images.githubusercontent.com/38770780/156689907-b3e994df-a811-4551-9c58-fcb344f5ca56.png)
In this image, you can see that the HBM block uses x16 sand instead of x32 like the sand in the rest of this shot. It would be nice if they textures that HBM uses works like the Pink Log so ores mineral its found in is seamless into blending in with the texturepacks resources, like this 

![image](https://user-images.githubusercontent.com/38770780/156690859-60661f4e-0e4f-4bce-9160-757708352886.png)
(you have to look closely to see the difference in this shot)

would be a nice QoL sort of thing

**Comment by SteamDoge9000** [comment]
Sidenote: it would also be useful if you do this to share some of the code for rendering the resource as a block in an inventory, my friend is having it render as one block and various subtypes that from based on what mineral it is, it works but theirs an issue with it working in inventory item render with it only rendering on one side. Some tips on this would be useful to correct this lil bug on my friends end

**Comment by SoB1nary** [comment]
could you, like, stop suggesting stuff, please?

**Comment by HbmMods** [comment]
Vanilla's block rendering doesn't have a built-in layer support like items do (except a hardcoded case for grass overlays because of course it's hardcoded) which means I'd have to make a new RenderBlock implementation that handles layers. And ever since the CT rendering fiasco I'd argue it'd be 50x faster to add NTM support to whatever texture pack you're using by just scribbling over 20 or so block textures compared to making dynamic rendering that in the end still looks weird because of 16px ore veins on a drastically different background.
