### ISSUE TITLE
[Nerf Recomendation] loot table for old reactor blocks

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#492]
### Describe the bug

To be honest, the issue here is that you can get too much if you go reward hunting, especially if you are in large desert biomes, but one thing that I continue to notice despite the changes is the old Reactor blocks, mining one will drop a TIER 3 military Circuit chip, and that can be divided into 2 advanced chips. Now let's look at things like the atom or vertibird crashes. hell, even the spaceship. there are numerous ones in each structure and this can lead to easy to acquire advanced circuits. 

my proposal: rework the reactor drops in the loot structures to have a loot table, with a tier 3 chip and various other random scrap being recovered once from each block mimed (fortune does not affect this rate of drops)

In my head, when you mind the legacy reactor block, you would most of the time get scrap (the item) and maybe uncommonly on occasion or so some ingots that once made it up. High-value items like tier 3 military circuits would be a rarer drop occurrence

and since I'm playing a testing run on 528 mode, I'd recommend making useless scrap (the item) more common than the ingots that could drop and their 3 chips even rarer.

**Comment by ncr-t** [comment]
Two things. 
1-You are still suggesting.
2-you didn’t take into account three things : « reward hunting » takes time, and can be laborious, it’s statistically  much faster to get the circuits yourself instead of hunting for materials. second thing, the tier 3 circuits are in no way as advanced as you say, as they don’t need any advanced components.third thing, if I recall correctly, structures were designed with the idea of making a less painful start, so you could get into the good part of the mod faster
