### ISSUE TITLE
[Feature] A power diode would be nice (or other power prioritisation)

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#525]
Something that only allows power to be directed one way would be rather helpful for circumstances where you want to *guarantee* power goes to one particular source first, regardless of what the net ends up deciding to do (I think currently you're fairly safe assuming power will drop off at "the closest location", but that gets a lot weirder to consider when you get to actual power nets people will build :P )

**Comment by HbmMods** [comment]
An interesting question for sure, the old power system had the inherent flaw that every machine would receive the exact same amount of power, even if it was above the remaining capacity, leading to cases where large amounts of power would simply not be transmitted (from low-capacity consumers) despite there still being plenty of demand (from other high-capacity users).

The new system no longer weights every consume the same, but instead depending on how much capacity there is left. Sounded fairer on paper, but it turns out buffering batteries with high capacity that are supposed to store excess energy end up stealing away power from lower capacity fusion reactors that desperately need the energy.

Good thing we're using the new energy system now, since I can probably make a sort of diode for creating artificial bottlenecks in the same fashion as the HE/RF converters work. Ideally easily configurable since tearing apart the entire power grid for minor adjustments sounds like a pain.

**Comment by thePalindrome** [comment]
I could also see a type of battery that is low priority and has configurable sides, as well as a threshold on when to output *to* said sides!

**Comment by Shibva** [comment]
this would be great for fluid pipes as well once they get updated as well, one way piping

**Comment by HbmMods** [comment]
Batteries have power prioritization now (instead of the crappy child safety lock for IO mode), allowing to switch between three priority modes (with all other machines being on medium by default), where higher priorities will pull as much energy as possible before the next lower level receives some. I'm leaving the issue open until I've added a priority toggle to diodes too (since that would allow to prioritize any machine or section of a power grid).

**Comment by Shibva** [comment]
tbh, that is great. imagine if the same could be done with fluid storage; though on a realistic level, idk how that would be logically apllied

**Comment by HbmMods** [comment]
Diodes have configurable priority options now, you can use a defuser to cycle through the three modes.
