### ISSUE TITLE
EnderIO Port

### ISSUE THREAD

**Issue by TheMiCraft** [HbmMods/Hbm-s-Nuclear-Tech-GIT#544]
I would appreciate it, when it would be possible to extract or insert fluid with EnderIO conduits.
Or is this already possible?

**Comment by ncr-t** [comment]
NTM doesn't support ForgeFluids, and might never do.

**Comment by TheMiCraft** [comment]
Why not?

**Comment by ncr-t** [comment]
coding is not just a matter or writing  two words and everything working, changing to forgefluid would mean rewriting 70% of the machines and system

**Comment by ncr-t** [comment]
and if YOU think it’s not that hard, go on, do that and make a pull request !

**Comment by TheMiCraft** [comment]
Ok, but is it not even possible to create a converter block?

**Comment by Vaern** [comment]
Notably, the fluid system was chosen specifically to allow for greater control on the player's behalf of which fluids go in what pipes. In forgefluids it might be possible to end up with multiple fluids clogging the same pipes, since the wanted fluid must travel through consistently to restrict said pipe to that fluid. In NTM, that's important when you'll often have numerous fluid pipes going next to eachother in the case of oil setups.

**Comment by Vaern** [comment]
> Ok, but is it not even possible to create a converter block?

Yeah, that would be practically impossible. I don't know if forgefluids has a system similar to oredict, but even if it does, NTM doesn't, and it would necessitate a weird and massive merging of the two systems just for a bit of limited functionality. Not exactly a good use of time; it would probably be better to go all the way in one direction or the other.

**Comment by TheMiCraft** [comment]
That's sad... But okay

**Comment by sdddddf80** [comment]
> 好吧，但难道连创建一个转换器模块都不可能吗？

well, if you want it, I have created a mod by CS3, which allows you to converter some fluids from hbmfluids to forgefluids(like water,lava,deuterium,oil,etc).I haven't added recipe for the converters yet, so you can add it as you wish.(PS. the converters are in the hbm machine tag)
[hbmplus.zip](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8403731/hbmplus.zip)

**Comment by sdddddf80** [comment]
> Ok, but is it not even possible to create a converter block?
well, if you want it, I have created a mod by CS3, which allows you to converter some fluids from hbmfluids to forgefluids(like water,lava,deuterium,oil,etc).I haven't added recipe for the converters yet, so you can add it as you wish.(PS. the converters are in the hbm machine tag)
[hbmplus.zip](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8403745/hbmplus.zip)

**Comment by sdddddf80** [comment]
> Ok, but is it not even possible to create a converter block?

well, if you want it, I have created a mod by CS3, which allows you to converter some fluids from hbmfluids to forgefluids(like water,lava,deuterium,oil,etc).I haven't added recipe for the converters yet, so you can add it as you wish.(PS. the converters are in the hbm machine tag
[hbmplus.zip](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8403748/hbmplus.zip)
)

**Comment by TheMiCraft** [comment]
Is this a ham Addons or is this hbm modified

**Comment by sdddddf80** [comment]
> Is this a ham Addons or is this hbm modified

it's a hbm addons

**Comment by sdddddf80** [comment]
> Ok, but is it not even possible to create a converter block?

wait，the hbm->mek fluid converter block's  describe is wrong. Both of the hbm fluid tank should be placed below and both of the mek fluid tank should be placed above.

**Comment by Drillgon200** [comment]
"Notably, the fluid system was chosen specifically to allow for greater control on the player's behalf of which fluids go in what pipes. In forgefluids it might be possible to end up with multiple fluids clogging the same pipes, since the wanted fluid must travel through consistently to restrict said pipe to that fluid. In NTM, that's important when you'll often have numerous fluid pipes going next to eachother in the case of oil setups."

Well this is just wrong. You can do the exact same thing with forge fluids, it just depends on how the pipe system handles it.

**Comment by TheMiCraft** [comment]
It doesnt worked for me
![2022-04-08_15 10 10](https://user-images.githubusercontent.com/54218430/162442395-2b7036a8-3596-4cdd-8d30-956075e57db3.png)

**Comment by sdddddf80** [comment]
> It doesnt worked for me ![2022-04-08_15 10 10](https://user-images.githubusercontent.com/54218430/162442395-2b7036a8-3596-4cdd-8d30-956075e57db3.png)

Actually you have to use hbm's small barrel😂.

**Comment by sdddddf80** [comment]
>Ok, but is it not even possible to create a converter block?

The mod which I sent you past has some bugs.Try this one.
[hbmplus.zip](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8461121/hbmplus.zip)
The converter block should be used like this
![1649339952_2_odjx](https://user-images.githubusercontent.com/53573250/162667574-e4af8220-b81c-4174-8f33-1fd632567b6b.jpg)
