### ISSUE TITLE
Ingot Duplication with Fortune Ability and Deco Blocks

### ISSUE THREAD

**Issue by Pessimismus** [HbmMods/Hbm-s-Nuclear-Tech-GIT#562]
The "Fortune" abiliy seems to work on all metal deco blocks, so instead of one you can get up to 3 ingots from one deco block when breaking it. Since you only need one ingot in the anvil to craft a deco block, I would call that a dupe glitch.

Testing:
![2022-04-09_1](https://user-images.githubusercontent.com/102322619/162573931-7ae8c196-db95-4406-8618-adb6f3be357a.png)

Result:
![2022-04-09_2](https://user-images.githubusercontent.com/102322619/162573955-b574d323-dba5-4db7-bcce-349ec6108a07.png)

Version: 1.0.27_X4193
Only NEI and NTM installed.

**Comment by Pessimismus** [comment]
btw: the Deco Light Emitter could use an upper beamwidth limit

![2022-04-09_14 26 49](https://user-images.githubusercontent.com/102322619/162574205-95b3cb06-1cf9-4499-beeb-1d571cd75616.png)

**Comment by HbmMods** [comment]
The issue with deco blocks is known and should already be fixed (although the fix is probably not in the latest release yet).

A size limit for beam emitters doesn't exist since if you, for whatever reason, need a beam this large then you should be able to make a beam this large. A base on a server I was on for example was supposed to have a similarly sized beam at the core.

**Comment by Pessimismus** [comment]
Sry, I searched if this issue was already reported but didn't find it.

Ah okay.

**Comment by HbmMods** [comment]
Should be fixed in X4200.
