### ISSUE TITLE
The ability to put one crate in another can cause problems with game client

### ISSUE THREAD

**Issue by luckybl0ck** [HbmMods/Hbm-s-Nuclear-Tech-GIT#572]
### Describe the bug

If you put several crates containing items into another one 20-30 times, the chunk may overload. Minecraft client will lag or even crash. Tested in a singleplayer and on a Thermos server. Mod version - X4200.

![IKP3db9anhE](https://user-images.githubusercontent.com/79654924/162994773-e9d8b3ad-906b-4fdb-8c89-2f11361ca076.jpg)

**Comment by HbmMods** [comment]
Stacking things with NBT inside other things and repeating that is a pretty common way of breaking the game. Simply preventing stacking crates inside each other won't work since you could simply use another mod's storage containers or backpacks and alternate those to bypass the restriction. If I end up fixing it it would probably have to somehow keep track of the NBT data's size.

**Comment by HbmMods** [comment]
Was fixed months ago, crates will drop their contents if a certain NBT threshold is exceeded.
