### ISSUE TITLE
Hadron circular mode doesn't include linear

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#573]
This is a (possible) regression from a few versions ago, but I'm only now getting around to this:

The implications of circular mode seem to imply that they'll include linear recipes, and I swear in older versions circular mode could do everything, but that seems to no longer be the case. The gui is really not helpful about that, since it just says "no recipe" when it fails. Then again, the linear vs. circular mode is a bit odd, since the cheapest recipe requires a circular hadron which at a minimum has more than ten times the requisite power (just due to build constraints, unless I'm missing something)

Either way, I feel the circular mode should "fall back" to linear mode recipes if there's no circular for the given inputs

**Comment by SoB1nary** [comment]
i think you have to enable linear mode in the hadron core? also isn't the cheapest recipe the creation of antimatter, which requires a linear hadron?

**Comment by thePalindrome** [comment]
That's rather my point, that I have to remember the antimatter recipe (as well as a few others) is linear-only, so while I had to make it circular to make my chicken nuggets, I have to flip it in the gui back to being linear to run those recipes or I'm told there is "no result", which is... quite a waste of some rather rare materials >.>

**Comment by HbmMods** [comment]
> I swear in older versions circular mode could do everything, but that seems to no longer be the case.

That was never the case, the particle would only ever match the recipe mode specified in the GUI. The entire point of the mode switch needing to be exact is that this allows different recipes for the same ingredients (which in retrospect was never needed so the modes are kind of unnecessary :P ).

> The gui is really not helpful about that, since it just says "no recipe" when it fails.

After #550 I added more "no recipe" messages detailing what exactly went wrong, similar to how error messages work (although more straight forward instead of with error codes) in addition to a stats tab which shows info on the last operation (status message, accelerator strength, position of the last error).

I'm not sure how exactly this should work, either the particle reaches the core again, counting the entire accelerator as "linear" (despite being a ring), making linear accelerators effectively useless, or the particle would only use the charge that it had when reaching the analysis chamber, effectively wasting the power that the accelerator used for the last stretch since anything from analysis to core wouldn't be counted. Then again, you can just skadoodle around that last point by simply having the analysis chamber right before the core so there's no meaningful difference between either mode. Perhaps I'll rework the thing (again) some day so that only some really high powered recipes need a linear accelerator while disallowing curves on those.

**Comment by HbmMods** [comment]
X4214 changed accelerator recipes so that circular accelerators can now do everything. So once you have a circular accelerator, you'll never have to change the mode. Linear recipes will also utilize the full accelerator and not just the length up to the analysis chamber.
