### ISSUE TITLE
Heat capacity issues (Mostly affects RBMK reactors)

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#585]
Several fluids' heat capacities have not been defined, which means they have a default value of 0, but are used in calculations within the mod. This causes issues like hot coolant not working in the heat exchanger (It doesn't produce any steam, and no hot coolant is converted into coolant. Mug coolant works fine, though) and RBMK boilers not decreasing their own temperatures when converting water into steam. Affects version X4214

**Comment by HbmMods** [comment]
Boilers are affected too? But those don't even use the heat capacity value and instead use a fixed number from one of the RBMK dials.

**Comment by TehTemmie** [comment]
This line: https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/fc79135be8822dfc0eb72157cfc58831c92d62bf/src/main/java/com/hbm/tileentity/machine/rbmk/TileEntityRBMKBoiler.java#L60

**Comment by HbmMods** [comment]
I'm reading through all of this again and nothing makes any sense whatsoever.

`TileEntityRBMKHeater` never actually references any fluids' heat capacity.

`TileEntityRBMKBoiler` does (but shouldn't), but only in one of the two required calculations and due to water not having a set heat capacity in theory it probably won't cool anything.

`TileEntityHeatex` seems to work perfectly, I guess?

`COOLANT_HOT` references `STEAM`'s heat capacity instead of `COOLANT`'s, resulting in it having none and not working in the heatex at all.

I don't remember binge drinking lately so idk what happened here.

**Comment by HbmMods** [comment]
Should be fixed now. I haven't double checked the current heat exchanger math so I'm leaving the issue open for now.

**Comment by HbmMods** [comment]
The current heat exchangers will be booted in favor of larger ones which use the much more consistent TU system, "fixing" the current tiny exchangers isn't necessary so I'm closing the issue.
