### ISSUE TITLE
crash with the new custom recipes

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#601]
[crash-2022-05-09_16.44.00-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8652717/crash-2022-05-09_16.44.00-client.txt)

**Comment by HbmMods** [comment]
What changes did you make to the recipe file?

**Comment by Sten89** [comment]
[hbmChemplant.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8653048/hbmChemplant.txt)

**Comment by ghost** [comment]
[hbmChemplant.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8653057/hbmChemplant.txt)
the recipes i added are at the bottom

**Comment by HbmMods** [comment]
You're missing an opening bracket for the item array on line 1103.

There is an unnecessary closing bracket for the fluid input array on line 1110.

Another closing bracket on line 1111.

The item input array on line 1112 only has a single string of text in it instead of an item array.

The fluid output on line 1113 is missing its array brackets.

Yet another bracket on line 1114.

The fixed file wold probably look like this:

[hbmChemplant.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8653220/hbmChemplant.txt)

Hard to verify that it actually works since without the items from all the other mods they don't load for me but at least the JSON is in a valid format and the other recipes load too.

**Comment by sdddddf80** [comment]
> You're missing an opening bracket for the item array on line 1103.
> 
> There is an unnecessary closing bracket for the fluid input array on line 1110.
> 
> Another closing bracket on line 1111.
> 
> The item input array on line 1112 only has a single string of text in it instead of an item array.
> 
> The fluid output on line 1113 is missing its array brackets.
> 
> Yet another bracket on line 1114.
> 
> The fixed file wold probably look like this:
> 
> [hbmChemplant.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8653220/hbmChemplant.txt)
> 
> Hard to verify that it actually works since without the items from all the other mods they don't load for me but at least the JSON is in a valid format and the other recipes load too.

Hi bob, I wonder if this Universal JSON recipe handling system can add new recipes or just change the recipes which are existing?

**Comment by HbmMods** [comment]
Recipes can be added, although new recipes for the chemical plant lack recipe icons and localization which may be added by editing the assets of the jar file.
