### ISSUE TITLE
small issues with crafting factory and chemical factory

### ISSUE THREAD

**Issue by TrueSanicWasHere** [HbmMods/Hbm-s-Nuclear-Tech-GIT#622]
![image](https://user-images.githubusercontent.com/38081161/172217455-b7a7202d-e380-4211-9440-2fc816e451fe.png)
![image](https://user-images.githubusercontent.com/38081161/172217465-91ec7a77-3848-49ba-a2da-280a85645b32.png)
![image](https://user-images.githubusercontent.com/38081161/172217469-bc7a8b4b-53d8-4055-b871-c2be72cb550f.png)
![image](https://user-images.githubusercontent.com/38081161/172217471-fc8ce3a4-ce98-4ae6-93d7-d66f7a97a55e.png)
![image](https://user-images.githubusercontent.com/38081161/172217477-af141029-6aeb-4e07-8ffb-1fd9d6009996.png)
![image](https://user-images.githubusercontent.com/38081161/172217481-d439bc6f-b40f-48a0-83b4-c96bc819de2d.png)
![image](https://user-images.githubusercontent.com/38081161/172217799-ec0aec3a-72b5-4005-a1f0-201a29c6f56f.png)
![image](https://user-images.githubusercontent.com/38081161/172217810-5442527d-4472-4cb1-a590-368b0ab84dc2.png)
![image](https://user-images.githubusercontent.com/38081161/172217814-1b4f3c19-77d8-4bbe-92a0-a33bd40dfd42.png)
![image](https://user-images.githubusercontent.com/38081161/172217816-5b8dab86-fca1-4750-860a-7a9afbfa5d71.png)

side note: in the ones where multiple slots are selected, the first one is favored (the one with the smallest "white number that appears when holding LAlt", not shown here for the sake of not cluttering the screen) 

in the ones where there are things placed in places where they _probably_ shouldn't be, i think not much explanation is needed

probably not much of a concern, i just made a test run of the machines as intended, which means **not manually** and it works properly

**Comment by HbmMods** [comment]
Not exactly a bug, vanilla expects each slot to be in a border totaling 18x18 pixels, but the GUI requires them to be at the bare minimum of 16x16. Unless I decided to rewrite the highlight rendering but I don't see that big of a need for that, especially since the assembly factory isn't really meant to be used manually.

Same goes for putting things into the output slot, you most likely have a crate or hopper connected which will void the item anyway.
