### ISSUE TITLE
Conveyor ejector filter not working and not pulling from certain blocks

### ISSUE THREAD

**Issue by stinkytoot200** [HbmMods/Hbm-s-Nuclear-Tech-GIT#631]
Version: 1.0.27X4263H1 (as of now, the latest version)

The filter for the conveyor ejector doesn't work. For example, when i have it set to filter only iron ingots from a furnace, it doesn't pull anything out, even when iron ingots are present.
Same thing for the blast furnace.

https://user-images.githubusercontent.com/86577879/174457118-0ffce827-ad97-45f2-ace4-487d136e82fc.mp4

The conveyor ejector also doesn't work at all for the arc furnace, whether the filter is on or not.

**Comment by HbmMods** [comment]
Ejectors follow the hopper IO rules, vanilla furnaces are defined so that input items can only be inserted at the top, fuel only at the side and output only works at the bottom. That's most likely the case since the system was meant for hoppers and hoppers can only extract from blocks above them.

NTM's basic furnaces mimic that behavior since until now there was no sideways IO possible. I should probably abandon the vanilla code in favor of one that is side-agnostic (the brand new iron furnace already works like this). As for the vanilla furnace, if it's really necessary I would have to add an exception to the hopper IO rules where it would ignore what the furnace has defined to allow extracting items sideways.

**Comment by stinkytoot200** [comment]
> Ejectors follow the hopper IO rules, vanilla furnaces are defined so that input items can only be inserted at the top, fuel only at the side and output only works at the bottom. That's most likely the case since the system was meant for hoppers and hoppers can only extract from blocks above them.
> 
> NTM's basic furnaces mimic that behavior since until now there was no sideways IO possible. I should probably abandon the vanilla code in favor of one that is side-agnostic (the brand new iron furnace already works like this). As for the vanilla furnace, if it's really necessary I would have to add an exception to the hopper IO rules where it would ignore what the furnace has defined to allow extracting items sideways.

That would be great, because then factories would be much more compact and straightforward. Thanks!

**Comment by HbmMods** [comment]
The newest version should have improved IO rules for vanilla, electric and arc furnaces. I'm leaving the issue open since there's probably a couple more machines that still need some work (the blast furnaces for example).
