### ISSUE TITLE
[enhancment[ sneaking "reverse placement logic" for belts

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#654]
### Describe the enhancement
(first time making a post like in a long while, don't screw it up and keep it an enhancment)

the new belts being added is sweet and all, but placing them down and forming a line can be a bit tedious with how they go when you place them, the idea is to include a belt being placed coming towards you if your holding sneak (shift). it would make the placement setup a bit less tedious

**Comment by HbmMods** [comment]
I'd like to avoid adding that behavior to sneaking because I found in tighter setups where conveyor lines end up going over machines, sneaking is required to actually place them, and in those cases the conveyors would end up being in reverse. There is however now an option to rotate (and bend) belts using the screwdriver.
