### ISSUE TITLE
Grapical issues when holding a item or mobs

### ISSUE THREAD

**Issue by Prisonca** [HbmMods/Hbm-s-Nuclear-Tech-GIT#665]
Newest edition has a bug where mobs get dark and character gets all fuzzy when holid any item

**Comment by SoB1nary** [comment]
what is in your modlist?

**Comment by HbmMods** [comment]
Does the issue persist in new worlds and with NTM removed?

**Comment by XXlilMASSACRE** [comment]
i am seeing this problem too i cannot hold any of the mod items without my screen turning a solid color. there is nothing in my mod list other than the mod itself. it also happens when trying to open my inventory. i have not touched the config files i just opened my world and it started happening. i cant escape it every time i open a new world it keeps happening

**Comment by HbmMods** [comment]
Could you remove the mod and see if it happens again? There's been plenty of reports like this one lately and from what I see it might be a general issue with forge, or perhaps even vanilla.

**Comment by XXlilMASSACRE** [comment]
yeah i think your right forge 1.7.10 without the mod is even worse it wont let me even generate a world without crashing

**Comment by HbmMods** [comment]
If it crashes right away this may be an unrelated problem, try lowering your render distance, with NTM installed it will fix an out of bound render distance slider.

What actually causes the screen glitch is hard to say, but it's only been happening somewhat recently and seems to affect the entire game.

**Comment by Herestmain** [comment]
You can try to roll back to the previous graphics driver, this problem may be caused by updating the graphics card driver

**Comment by HbmMods** [comment]
Collecting the GPU drivers issue in https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/issues/985
