### ISSUE TITLE
MY GAME CRASHES WHEN CREATING A NEW WORLD

### ISSUE THREAD

**Issue by gabx03** [HbmMods/Hbm-s-Nuclear-Tech-GIT#697]
it just happens in a big modpack that game crashes when generating a new world with the latest version of the mod, but not with an older one. i think it would be even useless to upload my latest crash report, because it lists each time a different mod, but hbm is always there. it first crashed with naturia, now BOP. pls help me, i can provide logs and crash reports of different istances of the game.

**Comment by gabx03** [comment]
the crashes always have like a common part each, that is: "Exception getting world type block" or something like that.

**Comment by gabx03** [comment]
and it looks like it has something to do with hbm oil spots and biomes o plenty, do not know what tho

**Comment by SoB1nary** [comment]
that's great, honey
now post a crash report

**Comment by gabx03** [comment]
[crash-2022-07-30_14.30.35-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9226494/crash-2022-07-30_14.30.35-server.txt)
[crash-2022-07-30_14.39.27-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9226495/crash-2022-07-30_14.39.27-server.txt)
[crash-2022-07-30_14.54.58-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9226496/crash-2022-07-30_14.54.58-server.txt)
[crash-2022-07-30_15.02.38-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9226497/crash-2022-07-30_15.02.38-server.txt)
[crash-2022-07-30_05.24.15-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9226498/crash-2022-07-30_05.24.15-server.txt)

I noticed that this happens when i put Vic's Modern Warfare mod in the modpack. the wierd thing is that this only happens when generating a new world, the worlds that I generated previously can be loaded without any problem.

**Comment by gabx03** [comment]
[crash-2022-07-30_15.09.11-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9226511/crash-2022-07-30_15.09.11-server.txt)
I tried to remove LOT mod, but this is the new crash report.

**Comment by gabx03** [comment]
this does not seem to be happening with this version of the mod 1.0.27_X3528. just providing more info, maybe we'll get to the root of the problem.

**Comment by HbmMods** [comment]
One of them seems to be caused by "Daventure" trying to generate an "Obsid Dungeon". NTM's not mentioned anywhere. See line 10:
`at com.codingcrusader.daventuremod.world.ObsidDungeon.generate_r0(ObsidDungeon.java:234)`.

The one thing these crashes do have in common is that the crash occours when trying to generate flowers, bushes or something that drops when not on grass:
`at com.hbm.blocks.generic.BlockNTMFlower.checkAndDropBlock(BlockNTMFlower.java:65)`
`at clashsoft.cslib.minecraft.block.BlockCustomPlant.checkFlowerChange(BlockCustomPlant.java:109)`
`at net.minecraft.block.BlockBush.func_149855_e(BlockBush.java:58)`

That appears to be identical to a report I've gotten last month, which also used BoP:
`at net.minecraft.world.SpawnerAnimals.func_77191_a(SpawnerAnimals.java:269)`

I suspect it's one of your coremods that somehow interfere with entity spawning. Several near identical crash logs I've found online all mention `WorldServerOF`, a part of optifine, I suggest starting with removing it.

**Comment by gabx03** [comment]
i managed to resolve it by putting the oil spawn in the hbm config to 0. i will try to remove OF, or change version, as you said, and see if that fixes it. thank you!

**Comment by gabx03** [comment]
do you need any more info? in case that can help you fixing these crashes.

**Comment by HbmMods** [comment]
If it happens again despite the oil spawn rate being at 0, please send me the crash reports. I'm not sure why this would happen with oil in particular since it's just a regular structure but if that's confirmed to be the issue then I can just change the oil spawn rules to something like the schist layers.

**Comment by gabx03** [comment]
alright, i will try to let you know!

**Comment by gabx03** [comment]
[crash-2022-07-30_19.20.06-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9226997/crash-2022-07-30_19.20.06-server.txt)
[crash-2022-07-30_19.26.00-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9226998/crash-2022-07-30_19.26.00-server.txt)

Do not know what happened, I actually changed nothing from where the game started working again, but these are the crashes. The first one is when i removed OF as you said, the second one is with an older version of OF. Actually, I am confused.

**Comment by HbmMods** [comment]
The first one seems to be an unrelated issue where `net.divinerpg.dimensions.vethea` is stuck in some sort of recursive loop trying to find a texture. The second one is the same error as before, but instead of an oil bubble it's the bedrock oil spot that seems to be involved here. I'm afraid unless you turn off most of NTM's world gen, you'll still run into this issue. Perhaps there's a bigger underlying issue, either with BOP or one of the other mods that aren't mentioned in the report? It's always some entity being spawned during world gen that fails.

**Comment by gabx03** [comment]
I honestly do not know. Actually i do not think that the divine rpg thing, is a fatal issue, because if i place the older version of hbm back, it does not crash, i do not think it is related to that. i will try to turn everything off and see what happens, if it does work, i hope the mod will still be playable somehow.

**Comment by gabx03** [comment]
[crash-2022-07-30_20.26.39-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9227087/crash-2022-07-30_20.26.39-server.txt)

after removing all ores, structures and eveything from config

**Comment by gabx03** [comment]
Ok, since i like your job so much, and it would be a pity removing your mod from the modpack, i think i found a way to help you fix the problem, cause from what i remember, the latest working version of the mod in my modpack (world generating whise, because while in the qorld it does work) is 1.0.27_X3528. after that version it started giving me problems, so when i'll be back home, i will let you know if that's confirmed, so maybe you know what you added after that version, and maybe, help you fix the problem! ;)

**Comment by Shibva** [comment]
I may not know much here, but I do have to ask, What world type are you generating? if its the default world gen or the BoP world gen option? regardless something is telling me that that BoP may itself be preventing it in some stupid modification issues. It could be possible that its not an oregen issue but more or less a PLANT gen issue and it clashing with the BoP foliage generation in some way.
