### ISSUE TITLE
Are you planning to add an animation of the nuclear reactor operation?

### ISSUE THREAD

**Issue by githubuser434** [HbmMods/Hbm-s-Nuclear-Tech-GIT#71]
maybe add cherenkov radiation?  
to make the startup of the nuclear reactor submerged into water look more realistic
like this:
![cherenkov-radiation](https://user-images.githubusercontent.com/66527840/87659155-6f374300-c75d-11ea-8c45-7856de818d75.jpg)

**Comment by HbmMods** [comment]
The best I could do is making the reactor light up when it's on, though since minecraft doesn't support colored lights, it wouldn't close to cherenkov radiation. A better approach would be adding rays to the reactor's rendering with additive blend functions, although minecraft's water is definitely going to conflict with that, making the light invisible from above the water surface. Overall, for such a small detail it's more trouble than it's worth.

**Comment by Drillgon200** [comment]
You could also add compatibility with a lightning mod like albedo so if that's installed, it would glow. Also seems like more effort than it's worth though.

**Comment by githubuser434** [comment]
you could make the glow that the DFC emits but blue

**Comment by Nos74** [comment]
![nikonium](https://user-images.githubusercontent.com/49816198/88147342-6ddd9e80-cbd3-11ea-972e-e8df72b1e114.gif)

**Comment by HbmMods** [comment]
As I explained, light effects using blend functions outright don't work underwater if viewed from above the surface, and the DFC uses just that. Cherenkov light isn't going to happen any time soon.
