### ISSUE TITLE
Certain blocks tend to not render properly with OptiFine

### ISSUE THREAD

**Issue by TrueSanicWasHere** [HbmMods/Hbm-s-Nuclear-Tech-GIT#716]
Issue: The aforementioned blocks tend to disappear when used in tandem with OptiFine, both with internal shaders and without. Both with internal shaders and without, no discernible **and** consistent pattern can be spotted behind said rendering issue. Out of multiple tests, one has resulted with the game crashing due to segfaulting (crash report can be found [here](https://pastebin.com/pkcR4Ycm)) (time has been changed to UTC+00:00 equivalent, otherwise identical to original)

Issue confirmed with:
All Deco blocks
Reinforced Glass
All Other in-game glass types from this mod (Boron, Lead, Uranium etc. including quartz glass)
All Hadron collider coils
Issue confirmed to occur to only this mod with OptiFine in use.
Issue confirmed for versions X4327, X4312

**Comment by HbmMods** [comment]
That's a long standing issue with OptiFine that also happens with other mods' connected textures like chisel. OF has a tendency to break with a lot of graphics related things because of the extent it modifies the base game, the segfault is most certainly an effect of the coremod (since without bytecode modification you're almost never going to run into a segfault). There's probably some graphics setting added by OF that might fix that, but I don't have any documentation at hand so it's hard to say which one.
