### ISSUE TITLE
SILEX / fel flickers, rendering the device unusable

### ISSUE THREAD

**Issue by Kezii** [HbmMods/Hbm-s-Nuclear-Tech-GIT#730]
### Describe the bug
The FEL laser seems to flicker, rendering the SILEX unusable since it can't complete the process

video:
![Peek 2022-09-03 23-53](https://user-images.githubusercontent.com/3357750/188288935-73d59f12-6642-46fe-9259-af9b5a041eb0.gif)

I found a workaround: it works when standing with the back on the laser and opening the silex from there

![immagine](https://user-images.githubusercontent.com/3357750/188289011-d1100238-8373-412c-9931-2627118814dc.png)

glass over the laser makes no difference

**Comment by LSK-LW** [comment]
I also have this problem in my server, maybe it's caused by a network problem?

**Comment by HbmMods** [comment]
Thermos servers are known to have this *fantastic* feature that is on by default where all tile entities that are not in a chunk that has a player in it only tick once a second instead of once per tick. If you happen to be on a server, either change its config for tile entity ticking or disable this "optimization" feature outright, if not then it might be an issue on my end.

**Comment by Kezii** [comment]
Editing the tileentities.yml file and disabilng the optimization on FEL and SILEX seems to have solved the issue, thanks!

**Comment by TheForge129** [comment]
low power
