### ISSUE TITLE
Enhancment: Better mud tank empying

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#743]
B.A.T.9000 should be able to dump a full tank of poisonous mud into it if there's enough room to dump as much as it can instead of having to repeat it.

this can be reserved for tanks that can hold a large amount of fluids

**Comment by SoB1nary** [comment]
hey i've got an enhancement for you:
shut the actual fuck up everyone fucking hates you
the below statement is actually my personal opinion but!
kill yourself

**Comment by Globalfirestorm10** [comment]
buddy, calm down, it's merely a suggestion.

**Comment by Globalfirestorm10** [comment]
> B.A.T.9000 should be able to dump a full tank of poisonous mud into it if there's enough room to dump as much as it can instead of having to repeat it.
> 
> this can be reserved for tanks that can hold a large amount of fluids
Bob doesn't accept suggestions or enhancements sadly

**Comment by ncr-t** [comment]
It’s not just a suggestion, it’s a suggestion from someone we have already yelled at for making to many suggestions, it’s tiring for everyone. and this shows how he haven’t learned anything. so here we are.

**Comment by Globalfirestorm10** [comment]
fair enough

**Comment by burningwater202** [comment]
He started off with suggestions, we said no suggestions, so then he disappeared for a bit. When he came back, he instead abused the “enhancements” tag as a thinly veiled attempt to throw more suggestions out, he was called out and stopped for a few months. Did the same thing with issue tickets too. Now he changed his name thinking that maybe we’d not think it was him, and just started back up where he left off with more suggestions. 

It’s well past being civil at this point, there’s really seemingly no way to actually get him to stop. If he wants something added to the mod, he can download from the repo and program it so that he can have his suggestions in his local version of the game without having to break rules to do so

**Comment by HbmMods** [comment]
The mud tank will most likely be removed, it's just a leftover from a time where there were no fluid pipes nor a unified fluid system and a high capacity container was needed. Please just stick to pipes instead.

**Comment by HbmMods** [comment]
mud tank dead (rip)

**Comment by burningwater202** [comment]
RIP mud tank
