### ISSUE TITLE
afriticial star item

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#746]
item made from different types of plasma and fusion fuel that creates a star made from blocks when dropped that can last for alot of time untill u drop too many iron into it it will create super strong explosion and also creates a blocks used to light big area and that turn ice into water and obsidian into lava but it has to be near star to turn obsidian or stone into lava or water into steam and can be used for create a better fusion reactor

**Comment by TheForge129** [comment]
Two things:
1. Suggestions aren't considered here
3. pls format properly as u can see if dont format properly it make it hard 2 read

**Comment by Antineutrino-4444** [comment]
if you know how to code stuff, you can just add in a pull request which will greatly increase the likelihood of your idea been added rather than proposing a suggestion in ISSUES. If you does not know, i think discussions can be a good place for you to propose your ideas, maybe some dude came across and conveniently knows how to code so that you will get a bobblehead :).
anyways, just saying that this is not a good place for suggestion that is vague and not really related to gameplay (no big effects)
