### ISSUE TITLE
energy convertor ded

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#762]
i was trying to power assembly machine and other things with coal generator from other mods result lead redstone wire conected to rf to he and he to rf convertor was doing litteraly nothing i placed other generators and wires result no results so please fix problem with energy conventor because it is litteraly deco block now

**Comment by burningwater202** [comment]
Can you send a screenshot of how you have it hooked up?

**Comment by burningwater202** [comment]
Maybe also try connecting the coal generator to a leadstone energy cell, then connect the RF to HE converter to that. On the other side of the RF to HE converter connect a red copper wire to your assembler and see if this works

**Comment by username90001** [comment]
i know how it works i was doing it 9999999999999999999999999999999 times result no results it is energy convertor broken

**Comment by HbmMods** [comment]
The issue is incorrect, the converters work just fine. The assembler has a general issue where placing a power source such as the converter right next to the connector doesn't work, instead a cable is required between the assembler and the power source. It's easy to replicate by using an RT cell, placing it right next to the assembler doesn't work, using a cable does.

**Comment by username90001** [comment]
no i meant i was testing it it doesnot work no matter what i will do it is jsut broken i was trying use ender io panels with thermal expansion energyh things and energy conventer conntected by wires to lithium accumulator result nothing
