### ISSUE TITLE
[1.0.27_X4417] Crash upon drinking nuka cola

### ISSUE THREAD

**Issue by Gronglegrowth** [HbmMods/Hbm-s-Nuclear-Tech-GIT#820]
### Describe the bug

When drinking nuka cola (or, presumably, any other item that would place a cap in the player's inventory), the game crashes. I'm assuming this is due to [Backhand](https://modrinth.com/mod/backhand) being installed, which backports the off-hand slot from the newer versions, but the crash report mentions Battlegear 2 which I do not have.

[Crashlog](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/10070513/crash-2022-11-22_14.27.40-client.txt)
And as title says, I am running mod version 1.0.27_X4417.

**Comment by HbmMods** [comment]
The lines mentioned in the stacktrace starting with `mods.battlegear2.api.core` actually do reference a package in the Backhand mod, more specifically part of its coremod that replaces some vanilla inventory behavior.

From what I can guess their implementation of `addItemStackToInventory (func_70441_a)` is limited to only work on servers, and NTM's bottles give you bottlecaps both on the client and server (instead of only on the server, then synchronizing the inventory). Should be easy enough to fix, although I'm not sure if there are any other NTM items that handle the inventory in that manner.

**Comment by HbmMods** [comment]
Version X4431 should fix this issue, although I haven't tested it with Backhend myself so I'm leaving the issue open for now.
