### ISSUE TITLE
Screen glitches out and turns to solid colors even when rolling back drivers

### ISSUE THREAD

**Issue by RandomMinecraftPlayer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#827]
The screen doesnt render properly when using the mod even when i roll back drivers

**Comment by OlorinIV** [comment]
Ok but how exactly improperly? Could you show a pic or at least describe it?

**Comment by HbmMods** [comment]
Does it still happen in a forge instance when you remove the mod?

**Comment by RandomMinecraftPlayer** [comment]
The screen turn to solid colors when holding a item. Depending on what im
looking at it changes colors, for example when looking at grass the screen
is green

**Comment by OlorinIV** [comment]
This quite a common problem. 
First check if you are using your discrete graphics card. Assuming that you are, and you still see this happen, I recommend rolling back your JVM version (like from 8u350->8u300), which is how I solved this issue. By the way I used Zulu 1.8.0_312 instead of Hotspot.
While NTM do mess with rendering sometimes, I doubt that this issue was actually NTM related. However, rolling back some graphics driver versions is still helpful in some other cases.
