### ISSUE TITLE
New fluid duct's incompatible with old fluid duct's and coated fluid duct's

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#839]
the fluid duct in the latest version does not connect with the old fluid duct's and the coated fluid duct, it also doesnt have a pipe end model so it just looks like a straight pipe

**Comment by redshadow3** [comment]
just noticed that they also connect to barrels that dont have a fluid set yet, they also dont really connect to barrels as the pipe ends before it reaches them leaving this gap
![2022-12-10_23 40 06](https://user-images.githubusercontent.com/106045016/206877993-a8c0d4a4-31e6-4ed2-956a-62389cab2fa3.png)

**Comment by redshadow3** [comment]
oh they also connect to barrels that arent the fluid that the duct is carrying

**Comment by Shibva** [comment]
im going to go out and say that this is intended, the old pipes are now LEGACY content and support is discontinued and that connection between old and new pipes are incompatable

for those that might like the old pipes, one could request a Retro version to be added that uses the new pipe system while maintaining a retro look

other than that Ill leave it for Bob, considering im not fully sure if this intentional or not

**Comment by redshadow3** [comment]
so how am i going to cover my pipes now? i cant use the coated ones cos they dont work with the new fluid duct system
