### ISSUE TITLE
[LOW PRIORITY] Bottles from non-water blocks

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#844]
### Describe the bug

this is a low level bug: fluid sources added in the mod such as Sulphuric Acid can be used to extract bottles of water from the source block and it might be fair to assume multiple other fluids added with source blocks in the mod may have the same behavior

**Comment by Howdidibreakit** [comment]
Yeah, in fluids, sulfuric acid seems to be some strange hybrid between water and acid, it has it's own texture file, but no code. I don't think other source blocks would do the same though, since sulfuric acid seems to be the ONLY fluid that the mods adds that doesn't have a .txt file. Along with how schrabidic acid, toxic ooze, corium, volcanic lava, and I think acid are all probably based off of the lava's code, I doubt they'd do the same thing as whatever mess sulfuric acid is made of.
