### ISSUE TITLE
[Fatal Bug] colorful leaves crash game when nuked (chromaticraft-interaction with NTM nuke mechanics)

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#854]
### Describe the bug

I have come across a bug when using little boy (expecting to see the new prototype mushroom cloud) and to see how it would handle on this laptop of mine, but instead, I've come across a fatal world bug when Chromaticraft leaves become falling blocks. While this issue is with Chromaticraft it is created with the mechanic of leaves and such becoming falling blocks. 

My proposed solution: except these sorts of things from becoming falling entities to prevent the crash from happing

Status of Bug: Critical; the world will become soft-locked until crashing falling blocks are removed

Crash report:
[crash-2022-12-22_06.06.04-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/10286407/crash-2022-12-22_06.06.04-server.txt)

**Comment by Shibva** [comment]
(apologies for title change spam, running on fumes here to fill this out before it slips my mind)

**Comment by Shibva** [comment]
upon futher testing it seems the leaves are ok, its the vine componet of the tree that seems to not like it

**Comment by HbmMods** [comment]
Just checked the code on both vanilla's falling blocks and ChromatiCraft's dye vines, apparently this happens due to the vines' `canReplace` method assuming that the passed stack is not null, while the vanilla falling block entity uses this method with a null parameter to check if the falling block can be placed as a static block. From what I can tell entirely unrelated to NTM, and it looks like it would probably affect falling blocks hitting vines in general. If you can reproduce the crash like that, it's best if you report it to Reika.

**Comment by Shibva** [comment]
Ok, thankyou for the clarification, I will go and do that

**Comment by Shibva** [comment]
@HbmMods this issue has been hopefuly resolved on their end now.
