### ISSUE TITLE
Automatic Mining Drill does not work below y=4, and Mining Laser doesn't work at all

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#872]
NTM Version: 1.0.27 X4474
The automatic mining drill does not mine blocks that are below y = 4 (blocks at y = 4 can still be mined). If the drill is placed above this height, the drill pipe will stop extending at y = 4, regardless of what's below. It will not mine any blocks directly below the pipe, either. If the base of the drill is placed at y = 4 or lower, the drill will error as shown: 
![2023-01-10_18 46 07](https://user-images.githubusercontent.com/36060353/211531680-790f8ded-2c1c-4ca8-bcd8-13db930f9ef3.png)
The mining laser appears to try to mine itself when turned on, and refuses to mine anything below it:
![2023-01-10_18 54 37](https://user-images.githubusercontent.com/36060353/211533163-e51e0594-9620-4f41-b3f6-80704b342cdb.png)

**Comment by HbmMods** [comment]
The mining drill stopping at Y:4 is intended, as do the oil pumps which work in almost the same way. Which turns out to be rather unfortunate considering bedrock coltan can spawn lower than that, making bedrock ores that spawn like that unobtainable. This probably doesn't need to be fixed since the dedicated bedrock coltan ores will be replaced with the generic bedrock ore that requires the large mining drill to extract, since that one has no trouble passing unbreakbale blocks without getting stuck and extending all the way to Y:0.

Not sure what's happening with the mining laser, the symptom is the same as the time when it got stuck trying to break those invisible RailCraft blocks, but it apparently happens all the time with regular air.

**Comment by HbmMods** [comment]
Fixed in X4476, mining lasers now work as expected and bedrock coltan is obtainable via the large mining drill.
