### ISSUE TITLE
Radiation and Nuclear Reactors

### ISSUE THREAD

**Issue by TheLithuanian** [HbmMods/Hbm-s-Nuclear-Tech-GIT#88]
After a nuclear reactor explodes, radiation lingers around for about a minute or so, and then it disappears entirely. Even near the green ooze where the reactor used to be. In earlier versions of this mod, radiation would consistently be around 8 RADS/s in the epicenter of the explosion and would gradually go down going further away, but it would still remain until the explosion would be fully cleaned up. So is the current disappearing radiation a bug, or a new feature?

**Comment by HbmMods** [comment]
The lingering radiation most likely came from trinitite and dead grass which used to give off environmental radiation. This has been removed since explosions, especially nukes, create thousands of dead grass blocks which would cause heavy server lag due to the blocks all ticking and updating radiation values. I might change how meltdowns work in the future, but for now radiation is only a temporary thing. Large nuclear reactors however don't fully explode, rather most of the fuel rods turn into sellafite which still have this block behavior, giving off radiation constantly.
