### ISSUE TITLE
Bug creating recipe?

### ISSUE THREAD

**Issue by Phillanor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#896]
I can't create a recipe. Deleting _ before the configuration file name didn't help. The server creates the file again. As a result, I have _hbmAssembler and just hbmAssembler, there is still no recipe.

**Comment by HbmMods** [comment]
The assembler config is the only one that will create a template file (the one with the underscore prefix) even if a recipe config is being used. If the recipes really don't show up, make sure that:
* Item names are spelled and formatted correctly
* The config file follows the JSON syntax
* All clients have the same config file as the server, since recipes aren't synchronized automatically
