### ISSUE TITLE
how to disable all explosion?

### ISSUE THREAD

**Issue by Phillanor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#904]
How can I turn off all explosions? from rockets, bombs and the like.  Not from the side of plugins, but from the side of the mod itself.

**Comment by Froooz** [comment]
>nuclear tech mod
>looks inside
>nukes
![HIM](https://user-images.githubusercontent.com/92550535/216191430-fd1d929b-9d8e-4e49-87ca-9ce612795427.png)

**Comment by HbmMods** [comment]
Dangerous drops can be disabled in the config, the items will simply despawn instead of exploding.

Nukes can be configured to have a smaller radius, although a radius of 0 or below isn't valid. The simplest way would be to remove the assembler recipes for the bombs if available and to use CraftTweaker for removing crafting table recipes. Using a plugin for banning items would probably be easier, but removing the recipes is the only other way.

Just remember that nuclear explosions are relevant to progression, the first batch of schrabidium can only be obtained by having fallout affect uranium ore.
