### ISSUE TITLE
[Cross-mod] Shredder only outputs one type of dust despise the ore input being different ores.

### ISSUE THREAD

**Issue by craft90** [HbmMods/Hbm-s-Nuclear-Tech-GIT#92]
N.B It appears to be a cross-mod issue. With only Nuclear Tech in the pack it functions like it should.

I noticed this quite annoying bug with the Shredder. If I attempt to shred multiple ores, the Shredder won't give their respective ore dusts. Instead it outputs only one kind of dust (the one first in line or the present dust in the ouput). E.g. if I attempt to shred iron and gold (vanilla) ores: the Shredder will process both ores but only output iron dust (somehow x4 it). This is making it impossible to shred multiple ores, regardless of source mod (even NuclearTech's own copper ore was misbehaving). Only time it gave another result was turning "Vic's modern warfare mod" copper into scrap (Don't ask me why... maybe it doesn't register it as an ore?). It doesn't differ between other types of copper ores, only outputting one kind of copper dust (which is good, don't get me wrong. But I'd prefer to have both iron and gold dust not just iron dust even if it's x4). Which happens to be whatever is loaded first (I imagine. In my first try it returned Thermal Expansion dust. With TE removed it returned Magnetic Craft dust. Loading order may be responsible.)

Oh and also I checked this in a clean instance (only NuclearTech) both with version 3598 and 3605, Forge 10.13.4.1614 No issues there. So it has to be a cross-mod issue.

Btw these are the tech mods beside Nuclear Tech that I use:
EnderCore (but not EnderIO. I don't know if it adds ores or just supports)
ExtraUtils
MagneticCraft
NuclearCraft
QuantumFlux (tho it only adds its own titanium ore)
Thermal suit (ThermalExpansion, ThermalFoundation (responsible for oregen), Thermal Dynamics, Thermal Recycling)
Voltz engine (required by ICBM and some other mod)
Vic's Modern Warfare Mod

Are there known incompatibility issues with any of these? Because while the focus is NuclearTech, I'd like having some supporting tech mods.

**Comment by HbmMods** [comment]
Shredder recipes are generated dynamically based on the ore dictionary, it will pair any "ore<Material>" with the first match to "dust<Material>", it just so happens that TE registers its dusts first. Usually, that's not a problem, and even if having a specific dust were required for some reason, TE among other mods has ore dict converters.

The shredder sometimes messing up recipes and yielding two of A instead of one A and one B is a year old bug that I could never found out. I looked into it a minute ago: Apparently it's an unfortunate collision of two oversights:

1. Before starting a new output stack, shredders will try to increment the stack size of an existing output stack, if the item matches. Note that this does not take into account metadata, which is something I didn't think of back in the day because I insist on making most resource items into actual separate items instead of one item with metadata (like dye or skull items)
2. Thermal uses one item for all its powders which only differ in metadata. Therefore, the shredder believes these outputs are equal and crams all of them into the same stack.

Thank you for bringing this to my attention, I was under the impression that I had fixed this quite recently (I did *something* but seemingly not what was necessary).

About VMW's ores: From what I've seen, half of them aren't registered in the ore dictionary, so the game can't possibly know that it should treat VMW copper the same way as other copper ingots. I believe it's the same way for their titanium, but not steel.

I'm not going to close this issue just yet since it's not the first time I did something in regards to the shredder, only to fuck that up. I'll mark it as resolved once we know for a fact that the fix works.

**Comment by craft90** [comment]
Yeah I had a feeling about that. It's not the first time I've run into meta data related issues (been playing around with WorldEdit in the past...). I imagine it's a leftover from when item IDs had a hardcoded numerical maximum. Using meta data saves on IDs, I believe.
1.7.10 is a weird version, being stuck between the item IDs of 1.6.4 and the name IDs (like minecraft:iron_ore) of 1.8 and higher.

MagneticCraft might also have a meta data issue. It behaved oddly aswell when TE was removed. But I haven't tested it in detail. I'd realize that might not be something you can correct.
AE2 also use metadata for its dusts... gah. It even makes vanilla ores mess up.
Edit: out of all the tech mods that I've tested, all of them use meta values. Only your mod uses separate IDs.

As for Vic's Modern weapon mod, that does remind me that last time I played around with it I had similair issues. Like how I couldn't use materials from other mods. Maybe I ought to take it out. Your mod does add weapons after all, that should give enough umph to Minecraft.

**Comment by craft90** [comment]
It appears that this is still broken on version 3612.

**Comment by GODTM** [comment]
so this is great and all its fixed now but do you mind crushing my rock with a cock nigger

**Comment by GODTM** [comment]
this has been fixed my nigger now can you smash my rock with a cock

**Comment by GODTM** [comment]
why you delete my shit god am i not enough of a white man for you jim the fuck nut

**Comment by godtm3** [comment]
Nuclear_pashtet IS A STUPID SAND NIGGER

**Comment by HbmMods** [comment]
Should be fixed with X3731.
