### ISSUE TITLE
fluids in the laser mining drill's range get turned into sandbags and mined (possible not-issue)

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#924]
when there is a fluid in the mining laser's way the fluid gets turned into sand bag blocks and then mined by it without the sand bag blocks being collected, is this an intended feature? and if yes it should be toggleable as it removes the ability of making automatic cobblestone generators

**Comment by redshadow3** [comment]
you can still make an automatic cobblestone generator with that but it does complicate things as you need to make a redstone thingy that will make and then push out the cobblestone infront of itself, but im not sure everyone knows how to do that

**Comment by HbmMods** [comment]
> when there is a fluid in the mining laser's way the fluid gets turned into sand bag blocks

That is to block off underground lakes from flooding the borehole, having water or lava down there could cause unnecessary lag, destroy mined items, etc.

> and then mined by it without the sand bag blocks being collected

Sand bags only exist as a means for machines to block fluids and are created out of thin air, it is neither necessary nor logical for them to drop anything.

> and if yes it should be toggleable as it removes the ability of making automatic cobblestone generators

The mining laser is neither intended to be used as a cobblestone generator, nor does it make sense to use it as one considering how expensive and late in the game it is compared to for example the automatic mining drill, as well as cobblestone generators from other mods. At least in the context of the mod there isn't much reason to make a cobblestone generator anyway, since you'll get more than enough from just using the mining laser as intended.

>  you need to make a redstone thingy that will make and then push out the cobblestone infront of itself

*Or that,* which is only takes a repeater and a regular piston to do.
