### ISSUE TITLE
Tsar Bomba takes 20 minutes to explode or even doesnt work

### ISSUE THREAD

**Issue by lIGrxmRxpxxrIl** [HbmMods/Hbm-s-Nuclear-Tech-GIT#934]
so everytime i explode a tsar bomba it explodes 20 minutes or even doesnt work pls fix that problem                                        

btw congrats hbmmods the new ivy mike model is so good and the new destruction from the bombs i so GOOD I LOVE THIS MOD

**Comment by Antineutrino-4444** [comment]
It is very likely that you have got a bad pc.
Tsar bomba is an extremely big bomb and it requires a large amount of calculation (unlike other huge bombs like tom and prototype), meaning you have to get a pretty decent pc for it to work. So, you either get a better pc or wait for the explosion to happen!

**Comment by lIGrxmRxpxxrIl** [comment]
Bro wtf so a 3060 ti and a 11900k 32gb ram is a bad pc?

**Comment by lIGrxmRxpxxrIl** [comment]
btw i exploded the biggest  possible thermonuclear custom nuke with 100fps constant

**Comment by Antineutrino-4444** [comment]
??? that makes no sense

**Comment by Antineutrino-4444** [comment]
my own little macbook air with an M2 chip and a 8g ram can get the tsar working at most 5 minutes
if this is the case i dont know what might caused this... maybe bob can explain everything...

**Comment by ncr-t** [comment]
the tsar bomba doesn't work properly 50% of the time anyway. IIGrxm are you sure you are running the last version ?

**Comment by Antineutrino-4444** [comment]
> IIGrxm are you sure you are running the last version ?
This can be a possibility, since bob changed the code for explosion loading and such a few versions ago, the latest code should be better. However, the previous code shouldnt be that bad, so something definitely have gone wrong.

**Comment by ncr-t** [comment]
it was definitely « that bad »

**Comment by HbmMods** [comment]
> Bro wtf so a 3060 ti and a 11900k 32gb ram is a bad pc?

Neither the GPU nor RAM affect the speed at all and your i9 doesn't really mean much when the game only runs on a single core.

> few versions ago, the latest code should be better

The new explosion algorithm only changes the way blocks are removed, the blast resistance checks which take the longest are still mostly the same (other than using the spiral point algorithm which is only marginally faster). Honestly considering that the Tsar can affect ~200 million blocks, having it process >150,000 a second doesn't sound all that bad. I believe the original version of the MK4 took about 45 minutes for the Tsar.

> or even doesnt work

That usually happens when the explosion entity unloads, explosions hold a ton of data which can't be saved and they don't load chunks on their own either.

**Comment by lIGrxmRxpxxrIl** [comment]
I don't want to be annoying or fussy, but why does it take half a minute to let large bombs (thermonuclear bombs) explode?

**Comment by burningwater202** [comment]
Because Java is unoptimized and Minecraft is unoptimized and running such a heavy calculation takes a lot of horsepower 

ever set off 50,000 TNT? It takes like 10 minutes to do but does the same amount of damage just about. The fact that they take 30 seconds in Java is a miracle in and of itself

**Comment by lIGrxmRxpxxrIl** [comment]
alter ganz ehrlich ihr könnt doch alle deutsch wieso schreibe ich die ganze zeit auf english
