### ISSUE TITLE
Shredder recipes amount is limited

### ISSUE THREAD

**Issue by iocmet** [HbmMods/Hbm-s-Nuclear-Tech-GIT#955]
Version: `HBM-NTM-[1.0.27_X4525]`
If you will add some recipe to start of hbmShredder.json it will replace hbm recipes in end also if you will add recipe to end of json it will not appear in game
![image](https://user-images.githubusercontent.com/63492966/225402696-097d19ac-9f50-4575-bcf1-6570b80022ac.png)

**Comment by HbmMods** [comment]
Can you send me the shredder recipe file you use?

**Comment by iocmet** [comment]
[hbmShredder.json.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/11006973/hbmShredder.json.txt)

**Comment by HbmMods** [comment]
There seems to be an issue with the recipe loading where if an item does not exist, the loader will stop without printing an error. You might be able to fix this by checking all added recipes and whether the mods are still installed and if the item is correct.

![image](https://user-images.githubusercontent.com/16674258/226166555-f961699a-bb3a-457d-ac00-3a0c4298dbbb.png)

I don't have these, so I ran into the same issue. I'll also add a fix on my end so that invalid entries will no longer affect the correct ones.

**Comment by HbmMods** [comment]
Should be fixed now, please close the issue if it works on your end.

**Comment by iocmet** [comment]
Will check later
