### ISSUE TITLE
(ENHANCEMENT) Rename the Jet engine (turbofan)

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#976]
Jet engines irl are made for different purposes, a turbofan engine is mostly used in airliners to produce the most thrust most efficiently, so this is innacurate naming beacause turbofan's arent made to produce power at all, but thrust, instead it should be called the turboshaft beacause that type of jet engine is made to produce power.

**Comment by Antineutrino-4444** [comment]
for these type of problems, you can literally open up a pull request since this will only need changing a few language files.
this way, the chance of enhancement being accecpted will be much higher so you should try it out.

**Comment by redshadow3** [comment]
> for these type of problems, you can literally open up a pull request since this will only need changing a few language files. this way, the chance of enhancement being accecpted will be much higher so you should try it out.

idk how to program stuff so i cant

**Comment by burningwater202** [comment]
Last time I checked, changing a plain text language file isn’t programming

**Comment by redshadow3** [comment]
> Last time I checked, changing a plain text language file isn’t programming

last time i checked i didnt check where this jet engine is in the code

**Comment by redshadow3** [comment]
and i dont know how pull requests work

oh theyre about reversing changes not making changes, how am i gonna change the name through that then?

**Comment by BallOfEnergy1** [comment]
Uh, pull requests are for both adding to a parent project and reverting changes (if needed)..?
You don't need programming experience to change the name of a mod, only to know some basic things about how it works.

**Comment by BallOfEnergy1** [comment]
> last time i checked i didnt check where this jet engine is in the code

Also, if it was last time you checked you didn't check, then you just didn't check, which means you never attempted to find it at all.

**Comment by redshadow3** [comment]
> Uh, pull requests are for both adding to a parent project and reverting changes (if needed)..? 

i cant find where you actually change something beacause i keep getting smthing to compare the versions and see the changes but cant edit them

> You don't need programming experience to change the name of a mod

im not trying to change the name of the mod, im trying to change the name of the jet engine

**Comment by BallOfEnergy1** [comment]
What you have to do is:
1. Fork the mod,
2. Make your changes and do whatever you need to do,
3. Create a pull request from your fork to the primary mod
(Also, it was a small typo when I said mod, changing the name of an item still doesn't require much programming experience)

**Comment by HbmMods** [comment]
I know this is an important topic to some people, especially the aviation experts in the community (cough cough Blue Hat) but there are a few deciding factors that went into naming the jet engine in NTM "turbofan", and for that purpose I have created this table which should hopefully clear things up:

![grafik](https://user-images.githubusercontent.com/16674258/228864543-c2b48ea7-ef0e-40cc-9005-0cb39faa07c3.png)

But you may be asking, why a turbofan if turbofans are >typically< used for thrust instead of their rotational energy? Well thankfully NTM's jet engine does both, it is in fact the generator with the highest thrust in the entire mod. To visualize that, I have created this handy graph:

![grafik](https://user-images.githubusercontent.com/16674258/228863975-e0aa798d-98ec-483c-815f-964b7c751742.png)

(since there is no proper unit of thrust in Minecraft's crude physics engine nor an entirely realistic portrayal of things like air drag and falloff over distance, those values are in % compared to NTM's jet engine)

I hope that clears everything up!

**Comment by redshadow3** [comment]
that first table just says "beacause fan", and the name is turboFAN beacause it has a fan, so adding that it has a fan doesnt really count, air flow bypass is to cool the engine but otherwise its wasted energy, afterburners arent included in commercial turbofans (yes i know this is a post-apocalyptic nuclear facility in the game basically even though the only post-apocalyptic trait is nuclear mines and the dud bombs and maybe some buildings or... not much else) and the turbofan isnt "usually not for power production" beacause jet engines are usually not at all used for that, beacause irl you can instead sell the fuel for more money than using it for electricity, also a turbofan doesnt have a way to efficiently take energy from it,

shortened:
fan: only included in turbofans as they operate at higher altitudes and need to get extra air
Air flow bypass: for cooling as there aint a point in making a coolant system that will radiate the heat to the air around the plane anyway
external shaft: required if youre using it for power otherwise there isnt a way to use all its power
afterburner: not usually included in commercial planes and cant actually add more power as they burn fuel after the turbine stage
named "turbofan": why does that matter? is it cooler?
used to make power: you need the external shaft

second chart:
why does the fact turbofans are made for thrust instead of electrical power generation matter? it only means it wouldnt produce the electrical power and wouldnt work, also if thats the point then it should throw the exhaust gasses further away beacause thats what you want for a THRUST producing engine, this should also change with afterburner upgrades

**Comment by redshadow3** [comment]
i closed this as apparently its not supposed to be that realistic

**Comment by JameH2** [comment]
this whole issue makes me want to throw myself into a turbofan

**Comment by TheBlueHat1** [comment]
person who genuinely works (studies technically) in this field here. This is absolute bollocks and you should be ashamed of your smarty-pantsism. The NTM turbofan is in fact, a turbofan. It does have the turbine (which rotates, makes powers AND has a fan attached to it). I know it may come as a shock but combustion engines are also used in propulsion AND power generation, but the aforementioned does a better job on the count of the fact that it was made for this purpose in the first place. A turbofan (jet engine in simple terms) was made for the exclusive purpose of thrust, yes, but to power a giant hunk of aluminum punching distrails in the sky at mach 0.3, you need electrical power, and a lot of it. Thats where the *turbo* part of the *turbo*fan comes in. The turbine spins, and makes power like a genuine turbine would. It makes a lot of it, because a genuine plane would need a lot of power. It is in fact a jet engine, yes, renaming the in-game turbofan would be comparable to renaming the boiler to a microwave. The power generation is exxagerated, yes, but it still makes power like a real turbofan would.

By the way, the bypass is *not* made for cooling the engine. It's made so the entire engine doesn't rip itself apart with the force of the jet coming out of the turbine (alongside various other purposes, sometimes being better gas expansion; but certainly not cooling. The entire plane is quite practically a radiator.) I would not give it the 100% realistic seal of approval, but I would give it the "realistic enough" seal of approval.  Now go and put on the _regular_ pants instead of the _smarty_ ones, silly little goofball.
